#!/usr/bin/env bash
# Runs the AMS WAR on Apache Tomcat 9, on either JDK - two instances sharing one Tomcat install, so
# both can be up at once.
#
#   ./tomcat.sh jdk8  deploy      stop, copy in the freshly built WAR, start        (port 8080)
#   ./tomcat.sh jdk21 deploy                                                         (port 8081)
#   ./tomcat.sh <jdk> start | stop | restart | status
#   ./tomcat.sh <jdk> logs        follow the console log (application + Tomcat)
#
# Typical cycle:   ./build-jdk8.sh && ./tomcat.sh jdk8 deploy
#
# On macOS this hands over to ./tomcat-mac.sh, which downloads Tomcat and keeps its instances under
# ~/tools. Everything below it is the Git Bash version for the Windows WorkSpaces machine.
#
# Tomcat 9 rather than 10+: the application is Servlet 3.1 / JSP 2.3 on the javax.* namespace, and
# Tomcat 10 moved to jakarta.*. Tomcat 9 runs on both Java 8 and Java 21, and the WAR is Java 8
# bytecode, so one WAR serves both instances - which is why both instances come from tools\dl\
# tomcat9.zip and neither uses tomcat10.zip. That one is for the jakarta migration, not this WAR.
#
# The server supplies three things the WAR relies on, and each instance recreates them:
#   - the jdbc/amsInternalDS pool behind web.xml's resource-ref  -> a context descriptor, DBCP2
#     (it takes precedence over the META-INF/context.xml inside the WAR)
#   - the H2 driver the pool loads                                -> instance lib\
#   - the JVM options (Spring profile, timezone, encoding)        -> instance bin\setenv.bat
#
# C:\tools is wiped on a WorkSpaces restart. Everything missing is rebuilt from tools\dl\tomcat9.zip
# and the Maven repository on every run, so this needs nothing beyond a restored toolchain -
# .\restore-jdk8.ps1 in this repo, or ..\..\tools\setup-env.ps1 outside it.
set -euo pipefail

case "$(uname -s)" in
  Darwin) exec "$(cd "$(dirname "$0")" && pwd)/tomcat-mac.sh" "$@" ;;
esac

# Paths below are handed to Windows programs already in Windows form.
export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'

usage() { sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'; exit 1; }

JDK_NAME="${1:-}"
CMD="${2:-deploy}"
case "$JDK_NAME" in
  jdk8)  HTTP_PORT=8080; SHUTDOWN_PORT=8005 ;;
  jdk21) HTTP_PORT=8081; SHUTDOWN_PORT=8006 ;;
  *)     usage ;;
esac

HERE="$(cd "$(dirname "$0")" && pwd)"
TOOLS='C:\tools'
JDK="$TOOLS\\$JDK_NAME"
CATALINA_HOME="$TOOLS\\tomcat9"
CATALINA_BASE="$TOOLS\\tomcat-$JDK_NAME"
# tomcat9.zip, not tomcat10.zip: see the namespace note in the header. The dl folder is derived from
# this script's location (the repo sits at mysoftware\1-forge\ams, so it is two levels up) rather
# than hardcoded, so moving or copying the tree does not break it. Already a POSIX path, which is
# what [ -f ] and unzip below want.
DL="${AMS_DL:-$(cd "$HERE/../../tools/dl" && pwd)}"
ZIP="$DL/tomcat9.zip"
H2_JAR="$(cygpath -u "$TOOLS")/m2/com/h2database/h2/1.3.176/h2-1.3.176.jar"
WAR="$HERE/ams-internal/AssetManagementInternalWeb/target/AssetManagementInternalWeb.war"
APP='AssetManagementInternalWeb'
URL="http://localhost:$HTTP_PORT/$APP"

HOME_U="$(cygpath -u "$CATALINA_HOME")"
BASE_U="$(cygpath -u "$CATALINA_BASE")"

[ -f "$(cygpath -u "$JDK")/bin/java.exe" ] || { echo "!! no JDK at $JDK - run tools\\setup-env.ps1 first"; exit 1; }

export JAVA_HOME="$JDK" JRE_HOME='' CATALINA_HOME CATALINA_BASE

# ---------------------------------------------------------------- install
# Shared binaries, extracted once and flattened to a stable name, the same way setup-env.ps1
# handles the JDKs and Maven.
install_home() {
  [ -f "$HOME_U/bin/catalina.bat" ] && return
  [ -f "$ZIP" ] || { echo "!! missing $ZIP"; exit 1; }
  echo "==> extracting Tomcat to $CATALINA_HOME"
  local staging; staging="$(cygpath -u "$TOOLS")/_extract_tomcat"
  rm -rf "$staging" && mkdir -p "$staging"
  unzip -q "$ZIP" -d "$staging"
  rm -rf "$HOME_U" && mv "$staging"/apache-tomcat-* "$HOME_U" && rm -rf "$staging"
}

# The instance directory. Configuration is rewritten on every run so it always matches this
# script; data\, logs\ and webapps\ are left alone.
install_base() {
  mkdir -p "$BASE_U"/{bin,conf/Catalina/localhost,lib,logs,temp,webapps,work,data}
  for f in catalina.properties logging.properties web.xml context.xml; do
    [ -f "$BASE_U/conf/$f" ] || cp "$HOME_U/conf/$f" "$BASE_U/conf/$f"
  done

  [ -f "$H2_JAR" ] || { echo "!! no H2 driver at $H2_JAR - run a build first"; exit 1; }
  cp -u "$H2_JAR" "$BASE_U/lib/"

  # HTTP only: 8443 is already taken on this machine, and TLS is the reverse proxy's job anyway.
  cat > "$BASE_U/conf/server.xml" <<EOF2
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by ams/tomcat.sh - edits are overwritten on the next run. -->
<Server port="$SHUTDOWN_PORT" shutdown="SHUTDOWN">
  <Listener className="org.apache.catalina.startup.VersionLoggerListener"/>
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener"/>
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener"/>
  <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener"/>
  <Service name="Catalina">
    <Connector port="$HTTP_PORT" protocol="HTTP/1.1" connectionTimeout="20000"/>
    <Engine name="Catalina" defaultHost="localhost">
      <Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="false">
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt" pattern="%h %l %u %t &quot;%r&quot; %s %b"/>
      </Host>
    </Engine>
  </Service>
</Server>
EOF2

  # The same pool the WAR's META-INF/context.xml declares, with the H2 file placed under this
  # instance. One H2 file per instance - embedded H2 admits a single JVM, so two cannot share one.
  local db; db="$(cygpath -m "$BASE_U")/data/ams"
  cat > "$BASE_U/conf/Catalina/localhost/$APP.xml" <<EOF2
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by ams/tomcat.sh - edits are overwritten on the next run. -->
<Context>
  <Resource name="jdbc/amsInternalDS" auth="Container" type="javax.sql.DataSource"
            driverClassName="org.h2.Driver"
            url="jdbc:h2:$db;MVCC=TRUE;LOCK_TIMEOUT=5000;DB_CLOSE_ON_EXIT=FALSE"
            username="sa" password=""
            maxTotal="10" minIdle="5" maxIdle="10" maxWaitMillis="30000"
            defaultTransactionIsolation="READ_COMMITTED"
            validationQuery="SELECT 1 FROM DUAL" testOnBorrow="true"/>
</Context>
EOF2

  # The JVM options. catalina.bat calls this before it picks a JVM, so it is also what pins the
  # instance to its JDK regardless of the JAVA_HOME it was started with.
  printf '%s\r\n' \
    '@echo off' \
    'rem Generated by ams/tomcat.sh - edits are overwritten on the next run.' \
    "set \"JAVA_HOME=$JDK\"" \
    'set "JRE_HOME="' \
    "set \"TITLE=AMS Tomcat ($JDK_NAME) :$HTTP_PORT\"" \
    "set \"CATALINA_OPTS=-Xmx1g -Dspring.profiles.active=local -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Duser.timezone=America/New_York -XX:+ExitOnOutOfMemoryError -DAppLogDir=$CATALINA_BASE\\logs\"" \
    > "$BASE_U/bin/setenv.bat"
}

# ---------------------------------------------------------------- lifecycle
# Decided on the status code from stdout, not on curl's exit code. MSYS2_ARG_CONV_EXCL above stops
# Git Bash rewriting /dev/null to NUL, so this mingw64 curl cannot write the body and exits 23 even
# on a perfectly good response - which made every caller below believe the server was down: status
# always said "stopped", stop_server skipped the graceful shutdown and went straight to the force
# kill, and start could not tell that an instance was already up. %{http_code} still reaches stdout
# when the body write fails, and is 000 when the connection never happened.
running() {
  local code
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "http://localhost:$HTTP_PORT/" 2>/dev/null || true)"
  [ -n "$code" ] && [ "$code" != 000 ]
}

stop_server() {
  if running; then
    echo "==> stopping $JDK_NAME instance"
    "$HOME_U/bin/catalina.bat" stop >/dev/null 2>&1 || true
    for _ in $(seq 1 30); do running || break; sleep 1; done
  fi
  # A JVM that never opened its port (or ignored the shutdown command) still holds the H2 lock.
  # Matched on its logging config path: catalina.bat quotes -Dcatalina.base, and this path is both
  # unquoted and unique to the instance.
  powershell.exe -NoProfile -Command \
    "Get-CimInstance Win32_Process -Filter \"Name='java.exe'\" | Where-Object { \$_.CommandLine -like '*$CATALINA_BASE\\conf\\logging.properties*' } | ForEach-Object { Stop-Process -Id \$_.ProcessId -Force }" \
    >/dev/null 2>&1 || true
}

start_server() {
  echo "==> starting $JDK_NAME instance (console output: $CATALINA_BASE\\logs\\console.log)"
  # The JVM inherits these handles. Left on this shell's pipe, it blocks the first time the pipe
  # fills after the shell has gone - and log4j's console appender holds a lock while it writes,
  # so every request thread then hangs behind it. A file never fills.
  "$HOME_U/bin/catalina.bat" start >>"$BASE_U/logs/console.log" 2>&1 </dev/null
  # First start unpacks the WAR and builds and seeds the H2 schema, which is slow on this disk.
  printf '    waiting for %s ' "$URL/health"
  for _ in $(seq 1 120); do
    local code; code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "$URL/health" || true)"
    if [ "$code" = 200 ]; then echo "- up"; echo "==> $URL"; return; fi
    printf '.'; sleep 3
  done
  echo "- not up after 6 minutes; see $CATALINA_BASE\\logs"
  exit 1
}

deploy_war() {
  [ -f "$WAR" ] || { echo "!! no WAR at $WAR - build first (./build-$JDK_NAME.sh)"; exit 1; }
  echo "==> deploying $(cygpath -w "$WAR")"
  rm -rf "$BASE_U/webapps/$APP" "$BASE_U/webapps/$APP.war" "$BASE_U/work/Catalina/localhost/$APP"
  cp "$WAR" "$BASE_U/webapps/$APP.war"
}

case "$CMD" in
  deploy)  install_home; install_base; stop_server; deploy_war; start_server ;;
  start)   install_home; install_base; running && { echo "already running: $URL"; exit 0; }; start_server ;;
  stop)    stop_server; echo "==> $JDK_NAME instance stopped" ;;
  restart) install_home; install_base; stop_server; start_server ;;
  status)  if running; then echo "$JDK_NAME: running on $URL"; else echo "$JDK_NAME: stopped"; fi ;;
  logs)    tail -F "$BASE_U/logs/console.log" ;;
  *)       usage ;;
esac
