INSERT INTO AMS_LOADABLE_TYPES (TYPE_ID, TYPE_NAME, TYPE_CD, DESCRIPTION, SORT_ORDER) VALUES (1, 'AssetStatusType', 'ACTIVE', 'Active', 4);
INSERT INTO AMS_LOADABLE_TYPES (TYPE_ID, TYPE_NAME, TYPE_CD, DESCRIPTION, SORT_ORDER) VALUES (2, 'AssetStatusType', 'INSTALLED', 'Installed', 3);
INSERT INTO AMS_LOADABLE_TYPES (TYPE_ID, TYPE_NAME, TYPE_CD, DESCRIPTION, SORT_ORDER) VALUES (3, 'OrderStatusType', 'SUBMITTED', 'Submitted', 2);
