INSERT INTO AMS_SERVICES (SERVICE_ID, CUSTOMER_ID, SERVICE_TYPE_CD, SERVICE_STATUS_CD, START_DT, DESCRIPTION, CREATED_DT, CREATED_BY)
VALUES (3001, 1001, 'MGDROUTER', 'ACTIVE', SYSTIMESTAMP, 'Managed Router Service', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_SERVICES (SERVICE_ID, CUSTOMER_ID, SERVICE_TYPE_CD, SERVICE_STATUS_CD, START_DT, DESCRIPTION, CREATED_DT, CREATED_BY)
VALUES (3002, 1001, 'SDWAN', 'ACTIVE', SYSTIMESTAMP, 'SD-WAN Service', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_SERVICES (SERVICE_ID, CUSTOMER_ID, SERVICE_TYPE_CD, SERVICE_STATUS_CD, START_DT, DESCRIPTION, CREATED_DT, CREATED_BY)
VALUES (3003, 1002, 'MGDROUTER', 'TERMINATED', SYSTIMESTAMP, 'Managed Router Service', SYSTIMESTAMP, 'SEED');
