INSERT INTO AMS_ADDRESSES (ADDRESS_ID, ADDRESS_TYPE_CD, ADDRESS_LINE_1, CITY, ZIP_CODE, STATE_CD, COUNTRY_CD, VALIDATED_FL, CREATED_DT, CREATED_BY)
VALUES (4001, 'SHIP', '100 Main Street', 'Springfield', '62704', 'IL', 'US', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ADDRESSES (ADDRESS_ID, ADDRESS_TYPE_CD, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, ZIP_CODE, STATE_CD, COUNTRY_CD, VALIDATED_FL, CREATED_DT, CREATED_BY)
VALUES (4002, 'INSTALL', '2200 Corporate Parkway', 'Suite 400', 'Austin', '78701', 'TX', 'US', 'N', SYSTIMESTAMP, 'SEED');
