-- 5001: healthy, migratable, nothing in flight.
INSERT INTO AMS_ASSETS (ASSET_ID, CUSTOMER_ID, ASSET_TAG, LEGACY_ASSET_TAG, SERIAL_NUMBER, ASSET_TYPE_CD, ASSET_STATUS_CD, DATA_SOURCE_CD, INSTALL_ADDRESS_ID, MIGRATABLE_FL, EMERGENCY_REPL_FL, NEEDS_ATTENTION_FL, CREATED_DT, CREATED_BY)
VALUES (5001, 1001, 'AMS-000501', 'NW-9', 'SN-ALPHA-001', 'ROUTER', 'ACTIVE', 'AMS', 4002, 'Y', 'Y', 'N', SYSTIMESTAMP, 'SEED');
-- 5002: migratable flag set, but an open order blocks it.
INSERT INTO AMS_ASSETS (ASSET_ID, CUSTOMER_ID, ASSET_TAG, LEGACY_ASSET_TAG, SERIAL_NUMBER, ASSET_TYPE_CD, ASSET_STATUS_CD, DATA_SOURCE_CD, MIGRATABLE_FL, NEEDS_ATTENTION_FL, ATTENTION_REASON, CREATED_DT, CREATED_BY)
VALUES (5002, 1001, 'AMS-000502', 'NW-10', 'SN-ALPHA-002', 'ROUTERWIFI', 'INSTALLED', 'AMS', 'Y', 'Y', 'Configuration push failed', SYSTIMESTAMP, 'SEED');
-- 5003: migratable flag set, but its stored configuration is mismatched.
INSERT INTO AMS_ASSETS (ASSET_ID, CUSTOMER_ID, ASSET_TAG, SERIAL_NUMBER, ASSET_TYPE_CD, ASSET_STATUS_CD, DATA_SOURCE_CD, MIGRATABLE_FL, NEEDS_ATTENTION_FL, CREATED_DT, CREATED_BY)
VALUES (5003, 1001, 'AMS-000503', 'SN-ALPHA-003', 'LEGACYROUTER', 'ACTIVE', 'LEGACY', 'Y', 'N', SYSTIMESTAMP, 'SEED');
-- 5004: not migratable at all.
INSERT INTO AMS_ASSETS (ASSET_ID, CUSTOMER_ID, ASSET_TAG, SERIAL_NUMBER, ASSET_TYPE_CD, ASSET_STATUS_CD, DATA_SOURCE_CD, MIGRATABLE_FL, NEEDS_ATTENTION_FL, CREATED_DT, CREATED_BY)
VALUES (5004, 1001, 'AMS-000504', 'SN-ALPHA-004', 'SWITCH', 'DECOM', 'AMS', 'N', 'N', SYSTIMESTAMP, 'SEED');
-- 5005: belongs to a different customer; proves the customer-scoped lookups.
INSERT INTO AMS_ASSETS (ASSET_ID, CUSTOMER_ID, ASSET_TAG, SERIAL_NUMBER, ASSET_TYPE_CD, ASSET_STATUS_CD, DATA_SOURCE_CD, MIGRATABLE_FL, NEEDS_ATTENTION_FL, CREATED_DT, CREATED_BY)
VALUES (5005, 1002, 'AMS-000505', 'SN-BETA-001', 'ROUTER', 'ACTIVE', 'AMS', 'Y', 'N', SYSTIMESTAMP, 'SEED');
