INSERT INTO AMS_NCR_TYPES (NCR_ID, NCR_TYPE_CD) VALUES (9001, 'BANDWIDTH');
INSERT INTO AMS_NCR_TYPES (NCR_ID, NCR_TYPE_CD) VALUES (9002, 'SITETYPE');
INSERT INTO AMS_NCR_TYPES (NCR_ID, NCR_TYPE_CD) VALUES (9002, 'IPREADDR');
