/*
 * Acceptance gate. Runs as the last step of 00_init.sh and fails the container if anything is
 * wrong, rather than letting a half-built schema come up "healthy".
 *
 * The smoke calls at the end matter more than they look. Spring's StoredProcedure binds parameters
 * positionally and RdbmsOperation.compile() never reads database metadata, so a procedure whose
 * signature does not match the Java compiles fine, deploys fine, starts fine - and throws
 * ORA-06550 the first time a user clicks the button. Nothing else in the build checks it. These
 * calls are that check.
 *
 * Everything here rolls back, so validation leaves no rows behind.
 */
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK OFF

DECLARE
  l_errors    NUMBER;
  l_tables    NUMBER;
  l_sequences NUMBER;
  l_views     NUMBER;
  l_packages  NUMBER;
  l_bodies    NUMBER;
  l_invalid   NUMBER;

  PROCEDURE assert_equals(p_what IN VARCHAR2, p_expected IN NUMBER, p_actual IN NUMBER) IS
  BEGIN
    IF p_expected <> p_actual THEN
      RAISE_APPLICATION_ERROR(-20001,
        'VALIDATION FAILED: ' || p_what || ' expected ' || p_expected || ', found ' || p_actual);
    END IF;
    DBMS_OUTPUT.PUT_LINE('  ok   ' || RPAD(p_what, 28) || p_actual);
  END assert_equals;

  PROCEDURE assert_status(p_what IN VARCHAR2, p_expected IN VARCHAR2, p_actual IN VARCHAR2) IS
  BEGIN
    IF NVL(p_actual, '<null>') <> p_expected THEN
      RAISE_APPLICATION_ERROR(-20002,
        'VALIDATION FAILED: ' || p_what || ' expected status ' || p_expected
        || ', got ' || NVL(p_actual, '<null>'));
    END IF;
    DBMS_OUTPUT.PUT_LINE('  ok   ' || RPAD(p_what, 40) || p_actual);
  END assert_status;

BEGIN
  DBMS_OUTPUT.PUT_LINE('--- object counts ---');

  SELECT COUNT(*) INTO l_tables    FROM USER_TABLES;
  SELECT COUNT(*) INTO l_sequences FROM USER_SEQUENCES;
  SELECT COUNT(*) INTO l_views     FROM USER_VIEWS;
  SELECT COUNT(*) INTO l_packages  FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PACKAGE';
  SELECT COUNT(*) INTO l_bodies    FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PACKAGE BODY';

  assert_equals('tables',        35, l_tables);
  assert_equals('sequences',     18, l_sequences);
  assert_equals('views',          1, l_views);
  assert_equals('packages',       3, l_packages);
  assert_equals('package bodies', 3, l_bodies);

  -- An INVALID package body is the single most likely failure and is completely silent: SQL*Plus
  -- exits 0 after creating one.
  SELECT COUNT(*) INTO l_invalid FROM USER_OBJECTS WHERE STATUS <> 'VALID';
  IF l_invalid > 0 THEN
    DBMS_OUTPUT.PUT_LINE('--- invalid objects ---');
    FOR o IN (SELECT OBJECT_NAME, OBJECT_TYPE FROM USER_OBJECTS WHERE STATUS <> 'VALID') LOOP
      DBMS_OUTPUT.PUT_LINE('  ' || o.OBJECT_TYPE || ' ' || o.OBJECT_NAME);
    END LOOP;
  END IF;
  assert_equals('invalid objects', 0, l_invalid);

  SELECT COUNT(*) INTO l_errors FROM USER_ERRORS;
  IF l_errors > 0 THEN
    DBMS_OUTPUT.PUT_LINE('--- compilation errors ---');
    FOR e IN (SELECT NAME, LINE, POSITION, TEXT FROM USER_ERRORS ORDER BY NAME, SEQUENCE) LOOP
      DBMS_OUTPUT.PUT_LINE('  ' || e.NAME || ' ' || e.LINE || ':' || e.POSITION || ' ' || e.TEXT);
    END LOOP;
  END IF;
  assert_equals('compilation errors', 0, l_errors);
END;
/

-- Shipping windows are generated relative to SYSDATE by 07_seed/36, so unlike every other seed
-- row they can be seeded and still be useless: a generator that produced only past dates would
-- leave the last step of the ordering flow permanently empty with nothing to show it had failed.
--
-- What is asserted is that bookable future windows EXIST - not that none have aged into the past.
-- An earlier version failed the gate on any past window, which is right for the few minutes after a
-- fresh build and wrong every day after: windows age out by design, and on a database that has been
-- up a fortnight most of them have. That check turned an ordinary healthy schema into a hard
-- failure, so it is gone; the future count is the thing that actually decides whether the screen
-- has anything on it.
DECLARE
  l_future NUMBER;
  l_past   NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_future
    FROM AMS_TIMESLOTS
   WHERE CALL_TYPE_CD = 'SHIP' AND START_TM > SYSTIMESTAMP AND AVAILABLE_FL = 'Y';
  SELECT COUNT(*) INTO l_past
    FROM AMS_TIMESLOTS
   WHERE CALL_TYPE_CD = 'SHIP' AND START_TM <= SYSTIMESTAMP;

  IF l_future = 0 THEN
    RAISE_APPLICATION_ERROR(-20006,
      'VALIDATION FAILED: no bookable shipping windows in the future'
      || ' (' || l_past || ' have aged into the past - re-run 07_seed/36 to roll them forward)');
  END IF;
  DBMS_OUTPUT.PUT_LINE('  ok   bookable shipping windows                 ' || l_future
                       || CASE WHEN l_past > 0 THEN '  (' || l_past || ' aged out)' ELSE '' END);
END;
/

-- The same failure mode as above, for the installation and tech-line capacity generated by
-- 07_seed/37. Those two calendars are what the second half of the lifecycle runs on: with no
-- future slots an order can be placed but never scheduled, and the screen gives no hint why.
-- The fixed September 2025 slots from 07_seed/14 are deliberately left out of this - they are
-- past by design and exist for the DAO tests, so only the generated future ones are counted.
DECLARE
  l_install  NUMBER;
  l_techline NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_install
    FROM AMS_TIMESLOTS
   WHERE CALL_TYPE_CD = 'INSTALL' AND START_TM > SYSTIMESTAMP AND AVAILABLE_FL = 'Y';
  SELECT COUNT(*) INTO l_techline
    FROM AMS_TIMESLOTS
   WHERE CALL_TYPE_CD = 'TECHLINE' AND START_TM > SYSTIMESTAMP AND AVAILABLE_FL = 'Y';

  IF l_install = 0 THEN
    RAISE_APPLICATION_ERROR(-20007,
      'VALIDATION FAILED: no bookable installation windows in the future');
  END IF;
  IF l_techline = 0 THEN
    RAISE_APPLICATION_ERROR(-20007,
      'VALIDATION FAILED: no bookable tech-line windows in the future');
  END IF;
  DBMS_OUTPUT.PUT_LINE('  ok   bookable installation windows             ' || l_install);
  DBMS_OUTPUT.PUT_LINE('  ok   bookable tech-line windows                ' || l_techline);
END;
/

DECLARE
  l_status    VARCHAR2(30);
  l_message   VARCHAR2(400);
  l_window_id NUMBER;
  l_released  NUMBER;
  l_email_id  NUMBER;
  l_reserved  NUMBER;
  l_decom_id  NUMBER;
  l_when      TIMESTAMP := CAST(TRUNC(SYSDATE) + 7 AS TIMESTAMP);

  PROCEDURE assert_status(p_what IN VARCHAR2, p_expected IN VARCHAR2, p_actual IN VARCHAR2) IS
  BEGIN
    IF NVL(p_actual, '<null>') <> p_expected THEN
      RAISE_APPLICATION_ERROR(-20002,
        'VALIDATION FAILED: ' || p_what || ' expected ' || p_expected
        || ', got ' || NVL(p_actual, '<null>'));
    END IF;
    DBMS_OUTPUT.PUT_LINE('  ok   ' || RPAD(p_what, 44) || p_actual);
  END assert_status;
BEGIN
  DBMS_OUTPUT.PUT_LINE('--- AMS_SCHEDULING_PG ---');

  -- Timeslot 9702 is seeded capacity 2 / reserved 2. The race a mock cannot reproduce.
  AMS_SCHEDULING_PG.reserve_timeslot(9702, 777001, 'TECHLINE', l_when, 'validate',
                                     l_status, l_message);
  assert_status('reserve_timeslot on a full slot', 'NO_CAPACITY', l_status);

  -- 9701 is capacity 4 / reserved 1.
  AMS_SCHEDULING_PG.reserve_timeslot(9701, 777001, 'TECHLINE', l_when, 'validate',
                                     l_status, l_message);
  assert_status('reserve_timeslot with room', 'OK', l_status);

  SELECT RESERVED_COUNT INTO l_reserved FROM AMS_TIMESLOTS WHERE TIMESLOT_ID = 9701;
  IF l_reserved <> 2 THEN
    RAISE_APPLICATION_ERROR(-20003, 'RESERVED_COUNT should be 2, is ' || l_reserved);
  END IF;
  DBMS_OUTPUT.PUT_LINE('  ok   reserved count incremented to ' || l_reserved);

  -- Reserving again must not take a second place: a double-clicked form is not an error.
  AMS_SCHEDULING_PG.reserve_timeslot(9701, 777001, 'TECHLINE', l_when, 'validate',
                                     l_status, l_message);
  assert_status('reserve_timeslot repeated', 'OK', l_status);
  SELECT RESERVED_COUNT INTO l_reserved FROM AMS_TIMESLOTS WHERE TIMESLOT_ID = 9701;
  IF l_reserved <> 2 THEN
    RAISE_APPLICATION_ERROR(-20003, 'repeat reserve double-counted: ' || l_reserved);
  END IF;
  DBMS_OUTPUT.PUT_LINE('  ok   repeat reserve did not double-count');

  AMS_SCHEDULING_PG.cancel_timeslot(9701, 777001, 'TECHLINE', 'validate', l_status);
  assert_status('cancel_timeslot', 'OK', l_status);

  -- The whole reason AMS_TIMESLOT_RESERVATIONS exists: a second cancel must be harmless.
  AMS_SCHEDULING_PG.cancel_timeslot(9701, 777001, 'TECHLINE', 'validate', l_status);
  assert_status('cancel_timeslot repeated', 'NOT_RESERVED', l_status);
  SELECT RESERVED_COUNT INTO l_reserved FROM AMS_TIMESLOTS WHERE TIMESLOT_ID = 9701;
  IF l_reserved <> 1 THEN
    RAISE_APPLICATION_ERROR(-20003, 'double cancel corrupted the count: ' || l_reserved);
  END IF;
  DBMS_OUTPUT.PUT_LINE('  ok   double cancel left the count at ' || l_reserved);

  AMS_SCHEDULING_PG.reserve_timeslot(9701, 777001, 'BOGUS', l_when, 'validate',
                                     l_status, l_message);
  assert_status('reserve_timeslot bad entity type', 'INVALID_INPUT', l_status);

  -- Asset 5001 is ACTIVE with no decommission, so this creates one (id passed as 0, the way
  -- CalendarServiceImpl passes a Java null).
  AMS_SCHEDULING_PG.schedule_decommission(0, 5001, l_when, 'Y', 'validate', l_status);
  assert_status('schedule_decommission', 'OK', l_status);

  AMS_SCHEDULING_PG.schedule_decommission(0, 5001,
    CAST(TRUNC(SYSDATE) + 400 AS TIMESTAMP), 'N', 'validate', l_status);
  assert_status('schedule_decommission beyond window', 'OUTSIDE_WINDOW', l_status);

  SELECT DECOMMISSION_ID INTO l_decom_id
    FROM AMS_DECOMMISSIONS WHERE ASSET_ID = 5001 AND DECOM_STATUS_CD = 'SCHEDULED';
  AMS_SCHEDULING_PG.cancel_decommission(l_decom_id, 'validation', 'validate', l_status);
  assert_status('cancel_decommission', 'OK', l_status);

  DBMS_OUTPUT.PUT_LINE('--- AMS_NCR_SCHEDULING_PG ---');

  -- 9002 is SCHEDULED (open); 9001 is COMPLETED.
  AMS_NCR_SCHEDULING_PG.schedule_ncr(9002, l_when, 'validate', l_status);
  assert_status('schedule_ncr', 'OK', l_status);

  AMS_NCR_SCHEDULING_PG.schedule_ncr(9001, l_when, 'validate', l_status);
  assert_status('schedule_ncr on a closed request', 'NOT_OPEN', l_status);

  -- Asset 5003 has no installation address, so this resolves to the 'ALL' circuit region.
  -- Site type deliberately null: CalendarServiceImpl passes null when the request has no proposed
  -- configuration, and that has to be a valid booking rather than an error.
  AMS_NCR_SCHEDULING_PG.schedule_site_type_ncr(9002, 5003, NULL, l_when, 'validate',
                                               l_status, l_window_id);
  assert_status('schedule_site_type_ncr, null site type', 'OK', l_status);
  IF l_window_id IS NULL THEN
    RAISE_APPLICATION_ERROR(-20004, 'schedule_site_type_ncr returned no circuit window id');
  END IF;
  DBMS_OUTPUT.PUT_LINE('  ok   circuit window id returned: ' || l_window_id);

  AMS_NCR_SCHEDULING_PG.schedule_site_type_ncr(9002, 5003, 'NOT_A_TYPE', l_when, 'validate',
                                               l_status, l_window_id);
  assert_status('schedule_site_type_ncr bad site type', 'INVALID_SITE_TYPE', l_status);

  AMS_NCR_SCHEDULING_PG.cancel_site_type_ncr(9002, 5003, 'validation', 'validate',
                                             l_status, l_released);
  assert_status('cancel_site_type_ncr', 'OK', l_status);
  IF l_released < 1 THEN
    RAISE_APPLICATION_ERROR(-20004, 'cancel_site_type_ncr released nothing');
  END IF;
  DBMS_OUTPUT.PUT_LINE('  ok   circuit windows released: ' || l_released);

  AMS_NCR_SCHEDULING_PG.cancel_ncr_date(9001, 'validation', 'validate', l_status);
  assert_status('cancel_ncr_date on a closed request', 'NOT_OPEN', l_status);

  DBMS_OUTPUT.PUT_LINE('--- AMS_EMAIL_PG ---');

  -- Order 6002 belongs to customer 1001, which has an ORDERING and an INSTALL contact.
  AMS_EMAIL_PG.add_entity_email('ORDER', 6002, 'ORDCONF', 'validate', l_status, l_email_id);
  assert_status('add_entity_email', 'OK', l_status);
  IF l_email_id IS NULL THEN
    RAISE_APPLICATION_ERROR(-20005, 'add_entity_email queued nothing');
  END IF;
  DBMS_OUTPUT.PUT_LINE('  ok   queued email id: ' || l_email_id);

  -- Immediately again: every recipient is now inside the de-duplication window.
  AMS_EMAIL_PG.add_entity_email('ORDER', 6002, 'ORDCONF', 'validate', l_status, l_email_id);
  assert_status('add_entity_email deduplicated', 'SUPPRESSED', l_status);

  AMS_EMAIL_PG.add_entity_email('NOPE', 6002, 'ORDCONF', 'validate', l_status, l_email_id);
  assert_status('add_entity_email bad entity type', 'INVALID_ENTITY_TYPE', l_status);

  AMS_EMAIL_PG.add_entity_email('ORDER', 999999, 'ORDCONF', 'validate', l_status, l_email_id);
  assert_status('add_entity_email unknown entity', 'NOT_FOUND', l_status);

  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('AMS schema validated: all objects valid, all entry points callable.');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
