-- Customers with some history, so the home page and the order activity report have something to
-- show. Four customers, each parked at a different point in the lifecycle, with orders in every
-- state the report distinguishes: one that is busy and healthy, one with an order in flight and
-- another on hold, one with years of history and a saved draft, and one at end of life.
--
-- The same four customers the Oracle stack seeds from db/oracle/07_seed/38_AMS_DEMO_LIFECYCLE.sql,
-- with the same ids and account numbers, so a screen looks the same whichever database is behind
-- it. Submitted dates are relative to today, so the ages on the report stay plausible however old
-- the database file is. Ids sit in the demonstration range: above the core seed and far below
-- 100000, where the sequences start, so nothing the application creates can collide with them.
--
-- Demonstration tier, so this runs only on an empty database and only outside production.

-- ---------------------------------------------------------------------------------------- customers
INSERT INTO AMS_CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SHORT_NAME, ACCOUNT_NUMBER, CAN_SUBMIT_ORDERS_FL, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (1010, 'Northwind Coffee Roasters', 'NORTHWIND', '102550', 'Y', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SHORT_NAME, ACCOUNT_NUMBER, CAN_SUBMIT_ORDERS_FL, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (1011, 'Beacon Hill Physio', 'BEACONHILL', '103180', 'Y', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SHORT_NAME, ACCOUNT_NUMBER, CAN_SUBMIT_ORDERS_FL, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (1012, 'Lakeshore Legal Partners', 'LAKESHORE', '104725', 'Y', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SHORT_NAME, ACCOUNT_NUMBER, CAN_SUBMIT_ORDERS_FL, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (1013, 'Sundial Grocery Co-op', 'SUNDIAL', '105390', 'Y', 'Y', SYSTIMESTAMP, 'SEED');

-- An active service each: ordering needs the flag, an active customer AND an active service.
INSERT INTO AMS_SERVICES (SERVICE_ID, CUSTOMER_ID, SERVICE_TYPE_CD, SERVICE_STATUS_CD, START_DT, DESCRIPTION, CREATED_DT, CREATED_BY)
VALUES (3101, 1010, 'MGDROUTER', 'ACTIVE', DATEADD('DAY', -400, SYSTIMESTAMP), 'Managed Router Service', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_SERVICES (SERVICE_ID, CUSTOMER_ID, SERVICE_TYPE_CD, SERVICE_STATUS_CD, START_DT, DESCRIPTION, CREATED_DT, CREATED_BY)
VALUES (3102, 1011, 'MGDROUTER', 'ACTIVE', DATEADD('DAY', -60, SYSTIMESTAMP), 'Managed Router Service', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_SERVICES (SERVICE_ID, CUSTOMER_ID, SERVICE_TYPE_CD, SERVICE_STATUS_CD, START_DT, DESCRIPTION, CREATED_DT, CREATED_BY)
VALUES (3103, 1012, 'SDWAN', 'ACTIVE', DATEADD('DAY', -900, SYSTIMESTAMP), 'SD-WAN Service', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_SERVICES (SERVICE_ID, CUSTOMER_ID, SERVICE_TYPE_CD, SERVICE_STATUS_CD, START_DT, DESCRIPTION, CREATED_DT, CREATED_BY)
VALUES (3104, 1013, 'MGDROUTER', 'ACTIVE', DATEADD('DAY', -700, SYSTIMESTAMP), 'Managed Router Service', SYSTIMESTAMP, 'SEED');

-- ---------------------------------------------------------------------------------------- addresses
-- A shipping and an installation address per customer. ZIP codes are ones AMS_INSTALL_REGIONS
-- knows, so an installation can be booked for them.
INSERT INTO AMS_ADDRESSES (ADDRESS_ID, ADDRESS_TYPE_CD, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, ZIP_CODE, STATE_CD, COUNTRY_CD, ATTENTION_TO, VALIDATED_FL, CREATED_DT, CREATED_BY)
VALUES (4101, 'SHIP', '1420 NW Glisan Street', NULL, 'Portland', '97201', 'OR', 'US', 'Goods In', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ADDRESSES (ADDRESS_ID, ADDRESS_TYPE_CD, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, ZIP_CODE, STATE_CD, COUNTRY_CD, VALIDATED_FL, CREATED_DT, CREATED_BY)
VALUES (4102, 'INSTALL', '1420 NW Glisan Street', 'Roastery floor', 'Portland', '97201', 'OR', 'US', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ADDRESSES (ADDRESS_ID, ADDRESS_TYPE_CD, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, ZIP_CODE, STATE_CD, COUNTRY_CD, VALIDATED_FL, CREATED_DT, CREATED_BY)
VALUES (4103, 'SHIP', '88 Charles Street', 'Suite 2', 'Boston', '02108', 'MA', 'US', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ADDRESSES (ADDRESS_ID, ADDRESS_TYPE_CD, ADDRESS_LINE_1, CITY, ZIP_CODE, STATE_CD, COUNTRY_CD, VALIDATED_FL, CREATED_DT, CREATED_BY)
VALUES (4104, 'INSTALL', '88 Charles Street', 'Boston', '02108', 'MA', 'US', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ADDRESSES (ADDRESS_ID, ADDRESS_TYPE_CD, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, ZIP_CODE, STATE_CD, COUNTRY_CD, VALIDATED_FL, CREATED_DT, CREATED_BY)
VALUES (4105, 'SHIP', '311 South Wacker Drive', 'Floor 21', 'Chicago', '60601', 'IL', 'US', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ADDRESSES (ADDRESS_ID, ADDRESS_TYPE_CD, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, ZIP_CODE, STATE_CD, COUNTRY_CD, VALIDATED_FL, CREATED_DT, CREATED_BY)
VALUES (4106, 'INSTALL', '311 South Wacker Drive', 'Comms room 21C', 'Chicago', '60601', 'IL', 'US', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ADDRESSES (ADDRESS_ID, ADDRESS_TYPE_CD, ADDRESS_LINE_1, CITY, ZIP_CODE, STATE_CD, COUNTRY_CD, VALIDATED_FL, CREATED_DT, CREATED_BY)
VALUES (4107, 'SHIP', '2050 Westlake Avenue N', 'Seattle', '98101', 'WA', 'US', 'N', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ADDRESSES (ADDRESS_ID, ADDRESS_TYPE_CD, ADDRESS_LINE_1, CITY, ZIP_CODE, STATE_CD, COUNTRY_CD, VALIDATED_FL, CREATED_DT, CREATED_BY)
VALUES (4108, 'INSTALL', '2050 Westlake Avenue N', 'Seattle', '98101', 'WA', 'US', 'Y', SYSTIMESTAMP, 'SEED');

-- ---------------------------------------------------------------------------------------- contacts
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, PHONE_EXTENSION, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2101, 1010, 'Marguerite', 'Ovalle', 'marguerite.ovalle@example.test', '555-0210', '110', 'ORDERING', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2102, 1010, 'Tobias', 'Ferrand', 'tobias.ferrand@example.test', '555-0211', 'SHIPPING', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2103, 1010, 'Ines', 'Barragan', 'ines.barragan@example.test', '555-0212', 'INSTALL', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2105, 1011, 'Wren', 'Alcott', 'wren.alcott@example.test', '555-0220', 'ORDERING', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, PHONE_EXTENSION, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2107, 1011, 'Halvard', 'Pyne', 'halvard.pyne@example.test', '555-0221', '4', 'INSTALL', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, PHONE_EXTENSION, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2109, 1012, 'Cordelia', 'Nwachukwu', 'cordelia.nwachukwu@example.test', '555-0230', '2200', 'ORDERING', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2111, 1012, 'Petra', 'Lindqvist', 'petra.lindqvist@example.test', '555-0232', 'INSTALL', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2114, 1013, 'Bo', 'Ravensworth', 'bo.ravensworth@example.test', '555-0240', 'ORDERING', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2116, 1013, 'Nadia', 'Toussaint', 'nadia.toussaint@example.test', '555-0241', 'INSTALL', 'Y', SYSTIMESTAMP, 'SEED');

-- ---------------------------------------------------------------------------------------- assets
-- The devices the completed and in-progress orders are about.
INSERT INTO AMS_ASSETS (ASSET_ID, CUSTOMER_ID, ASSET_TAG, SERIAL_NUMBER, ASSET_TYPE_CD, ASSET_STATUS_CD, DATA_SOURCE_CD, INSTALL_ADDRESS_ID, MIGRATABLE_FL, EMERGENCY_REPL_FL, NEEDS_ATTENTION_FL, CREATED_DT, CREATED_BY)
VALUES (5101, 1010, 'AMS-005101', 'SN-NW-0001', 'ROUTER', 'ACTIVE', 'AMS', 4102, 'N', 'N', 'N', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ASSETS (ASSET_ID, CUSTOMER_ID, ASSET_TAG, SERIAL_NUMBER, ASSET_TYPE_CD, ASSET_STATUS_CD, DATA_SOURCE_CD, INSTALL_ADDRESS_ID, MIGRATABLE_FL, EMERGENCY_REPL_FL, NEEDS_ATTENTION_FL, CREATED_DT, CREATED_BY)
VALUES (5102, 1010, 'AMS-005102', 'SN-NW-0002', 'ROUTERWIFI', 'ACTIVE', 'AMS', 4102, 'N', 'N', 'N', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ASSETS (ASSET_ID, CUSTOMER_ID, ASSET_TAG, SERIAL_NUMBER, ASSET_TYPE_CD, ASSET_STATUS_CD, DATA_SOURCE_CD, INSTALL_ADDRESS_ID, MIGRATABLE_FL, EMERGENCY_REPL_FL, NEEDS_ATTENTION_FL, CREATED_DT, CREATED_BY)
VALUES (5103, 1012, 'AMS-005103', 'SN-LL-0001', 'ROUTER', 'ACTIVE', 'AMS', 4106, 'N', 'N', 'N', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_ASSETS (ASSET_ID, CUSTOMER_ID, ASSET_TAG, SERIAL_NUMBER, ASSET_TYPE_CD, ASSET_STATUS_CD, DATA_SOURCE_CD, INSTALL_ADDRESS_ID, MIGRATABLE_FL, EMERGENCY_REPL_FL, NEEDS_ATTENTION_FL, CREATED_DT, CREATED_BY)
VALUES (5104, 1013, 'AMS-005104', 'SN-SD-0001', 'ROUTER', 'INSTALLED', 'AMS', 4108, 'N', 'N', 'Y', SYSTIMESTAMP, 'SEED');

-- ---------------------------------------------------------------------------------------- orders
-- Every state the report distinguishes appears at least once. Dates are relative to today.

-- Northwind: busy and healthy - two done, one shipped, one booked, one just submitted.
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, ASSET_ID, SHIPPING_CARRIER_CD, TRACKING_NUMBER, SUBMITTED_DT, SHIPPED_DT, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6101, 'ORD-6101', 'NEW', 'COMPLETED', 1010, 5101, 'UPS', '1Z-NW-0001', DATEADD('DAY', -120, SYSTIMESTAMP), DATEADD('DAY', -114, SYSTIMESTAMP), 'N', 'Roastery core', 4101, 2101, 2102, 2103, DATEADD('DAY', -120, SYSTIMESTAMP), 'SEED');
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, ASSET_ID, SHIPPING_CARRIER_CD, TRACKING_NUMBER, SUBMITTED_DT, SHIPPED_DT, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6102, 'ORD-6102', 'UPGRADE', 'COMPLETED', 1010, 5102, 'FEDEX', '7489-NW-0002', DATEADD('DAY', -60, SYSTIMESTAMP), DATEADD('DAY', -55, SYSTIMESTAMP), 'N', 'Tasting room Wi-Fi', 4101, 2101, 2102, 2103, DATEADD('DAY', -60, SYSTIMESTAMP), 'SEED');
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, SHIPPING_CARRIER_CD, TRACKING_NUMBER, SUBMITTED_DT, SHIPPED_DT, REQUESTED_INSTALL_DT, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6103, 'ORD-6103', 'NEW', 'SHIPPED', 1010, 'UPS', '1Z-NW-0003', DATEADD('DAY', -9, SYSTIMESTAMP), DATEADD('DAY', -3, SYSTIMESTAMP), DATEADD('DAY', 5, SYSTIMESTAMP), 'N', 'Warehouse edge', 4101, 2101, 2102, 2103, DATEADD('DAY', -9, SYSTIMESTAMP), 'SEED');
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, SHIPPING_CARRIER_CD, SUBMITTED_DT, REQUESTED_INSTALL_DT, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6104, 'ORD-6104', 'NEW', 'SCHEDULED', 1010, 'UPS', DATEADD('DAY', -6, SYSTIMESTAMP), DATEADD('DAY', 4, SYSTIMESTAMP), 'N', 'Cold store sensor gateway', 4101, 2101, 2102, 2103, DATEADD('DAY', -6, SYSTIMESTAMP), 'SEED');
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, ASSET_ID, SHIPPING_CARRIER_CD, SUBMITTED_DT, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6105, 'ORD-6105', 'REPLACE', 'SUBMITTED', 1010, 5101, 'UPS', DATEADD('DAY', -2, SYSTIMESTAMP), 'N', 'Roastery core (replacement)', 4101, 2101, 2102, 2103, DATEADD('DAY', -2, SYSTIMESTAMP), 'SEED');

-- Beacon Hill: a first order being fulfilled, and an older one on hold while the lease is sorted.
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, SHIPPING_CARRIER_CD, SUBMITTED_DT, REQUESTED_INSTALL_DT, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6111, 'ORD-6111', 'NEW', 'FULFILL', 1011, 'FEDEX', DATEADD('DAY', -14, SYSTIMESTAMP), DATEADD('DAY', 7, SYSTIMESTAMP), 'N', 'Front desk router', 4103, 2105, 2105, 2107, DATEADD('DAY', -14, SYSTIMESTAMP), 'SEED');
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, SHIPPING_CARRIER_CD, SUBMITTED_DT, CANCEL_PENALTY_FL, COMMENTS, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6112, 'ORD-6112', 'NEW', 'ONHOLD', 1011, 'FEDEX', DATEADD('DAY', -30, SYSTIMESTAMP), 'N', 'Held until the second-floor lease is signed.', 'Treatment rooms AP', 4103, 2105, 2105, 2107, DATEADD('DAY', -30, SYSTIMESTAMP), 'SEED');

-- Lakeshore: years of history, a cancelled replacement, and a draft saved for later.
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, ASSET_ID, SHIPPING_CARRIER_CD, TRACKING_NUMBER, SUBMITTED_DT, SHIPPED_DT, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6121, 'ORD-6121', 'NEW', 'COMPLETED', 1012, 5103, 'UPS', '1Z-LL-0001', DATEADD('DAY', -400, SYSTIMESTAMP), DATEADD('DAY', -393, SYSTIMESTAMP), 'N', 'Floor 21 core', 4105, 2109, 2109, 2111, DATEADD('DAY', -400, SYSTIMESTAMP), 'SEED');
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, ASSET_ID, SHIPPING_CARRIER_CD, TRACKING_NUMBER, SUBMITTED_DT, SHIPPED_DT, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6122, 'ORD-6122', 'UPGRADE', 'COMPLETED', 1012, 5103, 'UPS', '1Z-LL-0002', DATEADD('DAY', -200, SYSTIMESTAMP), DATEADD('DAY', -195, SYSTIMESTAMP), 'N', 'Floor 21 core (SD-WAN upgrade)', 4105, 2109, 2109, 2111, DATEADD('DAY', -200, SYSTIMESTAMP), 'SEED');
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, ASSET_ID, SHIPPING_CARRIER_CD, SUBMITTED_DT, CANCELLED_DT, CANCELLATION_REASON, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6123, 'ORD-6123', 'REPLACE', 'CANCELLED', 1012, 5103, 'UPS', DATEADD('DAY', -45, SYSTIMESTAMP), DATEADD('DAY', -40, SYSTIMESTAMP), 'Fault cleared by a configuration push; replacement not needed.', 'N', 'Floor 21 core (replacement)', 4105, 2109, 2109, 2111, DATEADD('DAY', -45, SYSTIMESTAMP), 'SEED');
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, SHIPPING_CARRIER_CD, SUBMITTED_DT, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6124, 'ORD-6124', 'NEW', 'SAVED', 1012, 'UPS', DATEADD('DAY', -1, SYSTIMESTAMP), 'N', 'Floor 22 expansion', 4105, 2109, 2109, 2111, DATEADD('DAY', -1, SYSTIMESTAMP), 'SEED');

-- Sundial: end of life - the last install done, a replacement cancelled with a penalty.
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, ASSET_ID, SHIPPING_CARRIER_CD, TRACKING_NUMBER, SUBMITTED_DT, SHIPPED_DT, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6131, 'ORD-6131', 'NEW', 'INSTALLED', 1013, 5104, 'FEDEX', '7489-SD-0001', DATEADD('DAY', -20, SYSTIMESTAMP), DATEADD('DAY', -15, SYSTIMESTAMP), 'N', 'Tills and back office', 4107, 2114, 2116, 2116, DATEADD('DAY', -20, SYSTIMESTAMP), 'SEED');
INSERT INTO AMS_ORDERS (ORDER_ID, ORDER_NUMBER, ORDER_TYPE_CD, ORDER_STATUS_CD, CUSTOMER_ID, ASSET_ID, SHIPPING_CARRIER_CD, SUBMITTED_DT, CANCELLED_DT, CANCELLATION_REASON, CANCEL_PENALTY_FL, DEVICE_NICKNAME, SHIP_ADDRESS_ID, ORDER_CONTACT_ID, SHIP_CONTACT_ID, INSTALL_CONTACT_ID, CREATED_DT, CREATED_BY)
VALUES (6132, 'ORD-6132', 'REPLACE', 'CANCELLED', 1013, 5104, 'FEDEX', DATEADD('DAY', -5, SYSTIMESTAMP), DATEADD('DAY', -2, SYSTIMESTAMP), 'Store closing; decommission scheduled instead.', 'Y', 'Tills and back office (replacement)', 4107, 2114, 2116, 2116, DATEADD('DAY', -5, SYSTIMESTAMP), 'SEED');
