-- AMS_SERVICES
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_SERVICES (
  SERVICE_ID            NUMBER(19) NOT NULL,
  CUSTOMER_ID           NUMBER(19),
  SERVICE_TYPE_CD       VARCHAR2(20 CHAR),
  SERVICE_STATUS_CD     VARCHAR2(20 CHAR),
  START_DT              TIMESTAMP,
  END_DT                TIMESTAMP,
  DESCRIPTION           VARCHAR2(200 CHAR),
  EXTERNAL_SERVICE_REF  VARCHAR2(60 CHAR),
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR2(64 CHAR),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR2(64 CHAR),
  CONSTRAINT AMS_SERVICES_PK PRIMARY KEY (SERVICE_ID)
);
