-- AMS_EVENTS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_EVENTS (
  EVENT_ID           NUMBER(19) NOT NULL,
  EVENT_TYPE_CD      VARCHAR2(20 CHAR),
  ENTITY_TYPE_CD     VARCHAR2(20 CHAR),
  ENTITY_ID          NUMBER(19),
  DESCRIPTION        VARCHAR2(1000 CHAR),
  USER_ID            VARCHAR2(64 CHAR),
  USER_DISPLAY_NAME  VARCHAR2(120 CHAR),
  DATA_SOURCE_CD     VARCHAR2(20 CHAR),
  EVENT_DT           TIMESTAMP,
  CONSTRAINT AMS_EVENTS_PK PRIMARY KEY (EVENT_ID)
);
