-- AMS_ASSETS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_ASSETS (
  ASSET_ID            NUMBER(19) NOT NULL,
  CUSTOMER_ID         NUMBER(19),
  ASSET_TAG           VARCHAR2(40 CHAR),
  LEGACY_ASSET_TAG    VARCHAR2(40 CHAR),
  SERIAL_NUMBER       VARCHAR2(60 CHAR),
  ASSET_TYPE_CD       VARCHAR2(20 CHAR),
  ASSET_STATUS_CD     VARCHAR2(20 CHAR),
  DATA_SOURCE_CD      VARCHAR2(20 CHAR),
  INSTALL_ADDRESS_ID  NUMBER(19),
  MIGRATABLE_FL       VARCHAR2(1 CHAR) DEFAULT 'N',
  EMERGENCY_REPL_FL   VARCHAR2(1 CHAR) DEFAULT 'N',
  NEEDS_ATTENTION_FL  VARCHAR2(1 CHAR) DEFAULT 'N',
  ATTENTION_REASON    VARCHAR2(200 CHAR),
  CREATED_DT          TIMESTAMP,
  CREATED_BY          VARCHAR2(64 CHAR),
  MODIFIED_DT         TIMESTAMP,
  MODIFIED_BY         VARCHAR2(64 CHAR),
  CONSTRAINT AMS_ASSETS_PK PRIMARY KEY (ASSET_ID)
);
