-- AMS_EMAIL_QUEUE
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_EMAIL_QUEUE (
  EMAIL_ID         NUMBER(19) NOT NULL,
  TEMPLATE_CD      VARCHAR2(20 CHAR),
  ENTITY_TYPE_CD   VARCHAR2(20 CHAR),
  ENTITY_ID        NUMBER(19),
  TO_ADDRESS       VARCHAR2(200 CHAR),
  EMAIL_STATUS_CD  VARCHAR2(20 CHAR),
  FAILURE_REASON   VARCHAR2(1000 CHAR),
  CREATED_DT       TIMESTAMP,
  CREATED_BY       VARCHAR2(64 CHAR),
  MODIFIED_DT      TIMESTAMP,
  MODIFIED_BY      VARCHAR2(64 CHAR),
  CONSTRAINT AMS_EMAIL_QUEUE_PK PRIMARY KEY (EMAIL_ID)
);
