-- AMS_MODIFY_QUEUE
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_MODIFY_QUEUE (
  QUEUE_ID          NUMBER(19) NOT NULL,
  QUEUE_NAME        VARCHAR2(40 CHAR),
  ENTITY_REFERENCE  VARCHAR2(80 CHAR),
  PAYLOAD           VARCHAR2(4000),
  QUEUE_STATUS_CD   VARCHAR2(20 CHAR),
  ATTEMPT_COUNT     NUMBER(10) DEFAULT 0,
  FAILURE_REASON    VARCHAR2(1000 CHAR),
  CREATED_DT        TIMESTAMP,
  CREATED_BY        VARCHAR2(64 CHAR),
  MODIFIED_DT       TIMESTAMP,
  MODIFIED_BY       VARCHAR2(64 CHAR),
  CONSTRAINT AMS_MODIFY_QUEUE_PK PRIMARY KEY (QUEUE_ID)
);
