-- AMS_INSTALL_REGIONS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_INSTALL_REGIONS (
  ZIP_CODE   VARCHAR2(15 CHAR) NOT NULL,
  REGION_CD  VARCHAR2(20 CHAR),
  CONSTRAINT AMS_INSTALL_REGIONS_PK PRIMARY KEY (ZIP_CODE)
);
