-- AMS_ASSET_RETURNS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_ASSET_RETURNS (
  ASSET_RETURN_ID   NUMBER(19) NOT NULL,
  ASSET_ID          NUMBER(19),
  SERIAL_NUMBER     VARCHAR2(60 CHAR),
  RETURN_STATUS_CD  VARCHAR2(20 CHAR),
  CREATED_DT        TIMESTAMP,
  CREATED_BY        VARCHAR2(64 CHAR),
  MODIFIED_DT       TIMESTAMP,
  MODIFIED_BY       VARCHAR2(64 CHAR),
  CONSTRAINT AMS_ASSET_RETURNS_PK PRIMARY KEY (ASSET_RETURN_ID)
);
