-- AMS_DECOMMISSIONS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_DECOMMISSIONS (
  DECOMMISSION_ID     NUMBER(19) NOT NULL,
  ASSET_ID            NUMBER(19),
  DECOM_STATUS_CD     VARCHAR2(20 CHAR),
  REQUESTED_DT        TIMESTAMP,
  SCHEDULED_DT        TIMESTAMP,
  COMPLETED_DT        TIMESTAMP,
  REASON              VARCHAR2(400 CHAR),
  HARDWARE_RETURN_FL  VARCHAR2(1 CHAR) DEFAULT 'N',
  CREATED_DT          TIMESTAMP,
  CREATED_BY          VARCHAR2(64 CHAR),
  MODIFIED_DT         TIMESTAMP,
  MODIFIED_BY         VARCHAR2(64 CHAR),
  CONSTRAINT AMS_DECOMMISSIONS_PK PRIMARY KEY (DECOMMISSION_ID)
);
