-- AMS_CUSTOMER_EARLY_ADOPTERS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_CUSTOMER_EARLY_ADOPTERS (
  CUSTOMER_ID       NUMBER(19) NOT NULL,
  EARLY_ADOPTER_FL  VARCHAR2(1 CHAR) DEFAULT 'N',
  ENROLLED_DT       TIMESTAMP,
  PROGRAM_NAME      VARCHAR2(80 CHAR),
  CONSTRAINT AMS_CUSTOMER_EARLY_ADOPTERS_PK PRIMARY KEY (CUSTOMER_ID)
);
