-- AMS_CUSTOMERS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_CUSTOMERS (
  CUSTOMER_ID           NUMBER(19) NOT NULL,
  CUSTOMER_NAME         VARCHAR2(120 CHAR),
  CUSTOMER_SHORT_NAME   VARCHAR2(40 CHAR),
  ACCOUNT_NUMBER        VARCHAR2(20 CHAR),
  CAN_SUBMIT_ORDERS_FL  VARCHAR2(1 CHAR) DEFAULT 'N',
  ACTIVE_FL             VARCHAR2(1 CHAR) DEFAULT 'Y',
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR2(64 CHAR),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR2(64 CHAR),
  CONSTRAINT AMS_CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID)
);
