-- AMS_PROPERTIES
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_PROPERTIES (
  PROPERTY_KEY    VARCHAR2(60 CHAR) NOT NULL,
  PROPERTY_VALUE  VARCHAR2(400 CHAR),
  DESCRIPTION     VARCHAR2(400 CHAR),
  MODIFIED_DT     TIMESTAMP,
  MODIFIED_BY     VARCHAR2(64 CHAR),
  CONSTRAINT AMS_PROPERTIES_PK PRIMARY KEY (PROPERTY_KEY)
);
