package org.example.am.internal.utils;

/**
 * Session attribute keys, request parameter names and result codes shared by the internal web tier
 * and the internal services.
 */
public final class InternalConstants {

    /** Session attributes. */
    public static final String SESSION_AJAX_TOKEN = "ajaxToken";
    public static final String SESSION_CUSTOMER = "currentCustomer";
    public static final String SESSION_CURRENT_TIME_OVERRIDE = "currentTimeOverride";
    public static final String SESSION_ORDER_MODEL = "orderModel";
    public static final String SESSION_NCR_MODEL = "networkChangeRequestModel";

    /** Request parameters. */
    public static final String PARAM_AJAX_TOKEN = "ajaxToken";
    public static final String PARAM_CUSTOMER_ID = "customerId";
    public static final String PARAM_ASSET_ID = "assetId";
    public static final String PARAM_ORDER_ID = "orderId";

    /** Struts result names declared in the root {@code struts.xml}. */
    public static final String RESULT_CUSTOM_ERROR = "custom_error";
    public static final String RESULT_INVALID_TOKEN = "invalid.token";
    public static final String RESULT_INVALID_JSON_TOKEN = "invalid.json.token";
    public static final String RESULT_UNAUTHORIZED = "unauthorized";

    /** Address validation interceptor result names. */
    public static final String RESULT_AV_SUCCESS = "av.success";
    public static final String RESULT_AV_SUGGESTION = "av.suggestion";
    public static final String RESULT_AV_ERROR = "av.error";

    /**
     * Whitelist of characters accepted in any request parameter.
     *
     * <p>Applied by both the Struts interceptor and the Spring MVC handler interceptor, so a
     * request is checked whichever framework ends up serving it.</p>
     */
    public static final String SPECIAL_CHARACTER_WHITELIST =
            "[0-9A-Za-z\\s'.,\\-_:*@/#$()=%+&?^`|~]*";

    /**
     * Whitelist of characters accepted in a request parameter <em>name</em>.
     *
     * <p>The value whitelist plus square brackets, because a form that repeats a row posts indexed
     * properties - {@code subscriberPcs[0].hostName} - and those are generated by our own JSPs.
     * Brackets stay out of the value whitelist: no screen in this application produces one in a
     * value, so accepting them there would widen the surface for nothing.</p>
     *
     * <p>The index itself is checked separately, so that only a genuine index gets through and a
     * name cannot smuggle an OGNL expression inside the brackets.</p>
     */
    public static final String PARAMETER_NAME_WHITELIST =
            "[0-9A-Za-z\\s'.,\\-_:*@/#$()=%+&?^`|~\\[\\]]*";

    /**
     * What may appear between the brackets of an indexed parameter name: digits only.
     *
     * <p>Struts binds {@code foo[0].bar} through OGNL, and OGNL will happily evaluate whatever is
     * inside the brackets. Constraining it to an integer is what keeps that an array index rather
     * than an expression.</p>
     */
    public static final String PARAMETER_INDEX = "\\[[0-9]{1,3}\\]";

    /** Message bundle base names. */
    public static final String BUNDLE_MESSAGES = "messages";
    public static final String BUNDLE_APP_VERSION = "appVersion";

    private InternalConstants() {
        super();
    }
}
