INSERT INTO AMS_INSTALL_REGIONS (ZIP_CODE, REGION_CD) VALUES ('78701', 'CENTRAL');
INSERT INTO AMS_INSTALL_REGIONS (ZIP_CODE, REGION_CD) VALUES ('62704', 'CENTRAL');
INSERT INTO AMS_INSTALL_REGIONS (ZIP_CODE, REGION_CD) VALUES ('10001', 'NORTHEAST');
-- Enough of the map to demonstrate the flow. A ZIP that is not here has no engineer region, which
-- is a real state the shipping window screen has to handle rather than an error: the order is
-- still placeable, it just cannot be given a despatch window until the map is extended.
INSERT INTO AMS_INSTALL_REGIONS (ZIP_CODE, REGION_CD) VALUES ('73301', 'CENTRAL');
INSERT INTO AMS_INSTALL_REGIONS (ZIP_CODE, REGION_CD) VALUES ('60601', 'CENTRAL');
INSERT INTO AMS_INSTALL_REGIONS (ZIP_CODE, REGION_CD) VALUES ('02108', 'NORTHEAST');
INSERT INTO AMS_INSTALL_REGIONS (ZIP_CODE, REGION_CD) VALUES ('19103', 'NORTHEAST');
INSERT INTO AMS_INSTALL_REGIONS (ZIP_CODE, REGION_CD) VALUES ('97201', 'WEST');
INSERT INTO AMS_INSTALL_REGIONS (ZIP_CODE, REGION_CD) VALUES ('98101', 'WEST');
INSERT INTO AMS_INSTALL_REGIONS (ZIP_CODE, REGION_CD) VALUES ('94105', 'WEST');
