INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, PHONE_EXTENSION, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2001, 1001, 'Dana', 'Whitfield', 'dana.whitfield@example.test', '555-0110', '204', 'ORDERING', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2002, 1001, 'Ray', 'Okonkwo', 'ray.okonkwo@example.test', '555-0111', 'SHIPPING', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PHONE_NUMBER, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2003, 1001, 'Priya', 'Raman', 'priya.raman@example.test', '555-0112', 'INSTALL', 'Y', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2004, 1001, 'Ex', 'Employee', 'ex.employee@example.test', 'TECH', 'N', SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_CONTACTS (CONTACT_ID, CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, CONTACT_TYPE_CD, ACTIVE_FL, CREATED_DT, CREATED_BY)
VALUES (2005, 1002, 'Sam', 'Delacroix', 'sam.delacroix@example.test', 'ORDERING', 'Y', SYSTIMESTAMP, 'SEED');
