INSERT INTO AMS_MODIFY_QUEUE (QUEUE_ID, QUEUE_NAME, ENTITY_REFERENCE, PAYLOAD, QUEUE_STATUS_CD, ATTEMPT_COUNT, CREATED_DT, CREATED_BY)
VALUES (9601, 'CONFIG_PUSH', 'ASSET:5002', '{}', 'NEW', 0, SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_MODIFY_QUEUE (QUEUE_ID, QUEUE_NAME, ENTITY_REFERENCE, PAYLOAD, QUEUE_STATUS_CD, ATTEMPT_COUNT, CREATED_DT, CREATED_BY)
VALUES (9602, 'CONFIG_PUSH', 'ASSET:5003', '{}', 'RETRY', 2, SYSTIMESTAMP, 'SEED');
INSERT INTO AMS_MODIFY_QUEUE (QUEUE_ID, QUEUE_NAME, ENTITY_REFERENCE, PAYLOAD, QUEUE_STATUS_CD, ATTEMPT_COUNT, CREATED_DT, CREATED_BY)
VALUES (9603, 'CONFIG_PUSH', 'ASSET:5001', '{}', 'COMPLETED', 1, SYSTIMESTAMP, 'SEED');
