-- Two groups that map to real roles, one that maps to a role this release does not define, and one
-- mapping that is switched off. Between them they cover every branch in the role resolution.
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_SEARCH_ASSETS', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_ASSET', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_ADMIN_UTILITIES', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_SEARCH_ASSETS', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_LEGACY', 'INT_RETIRED_ROLE', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_SUSPENDED', 'INT_CANCEL_ORDER', 'N');

INSERT INTO AMS_USERS (USER_ID, EMAIL_ADDRESS, DISPLAY_NAME) VALUES ('opsuser', 'ops.user@example.test', 'Ops User');

INSERT INTO AMS_CUSTOMER_VISITS (USER_ID, CUSTOMER_ID, VISITED_DT) VALUES ('opsuser', 1002, TIMESTAMP '2025-08-01 09:00:00');
INSERT INTO AMS_CUSTOMER_VISITS (USER_ID, CUSTOMER_ID, VISITED_DT) VALUES ('opsuser', 1001, TIMESTAMP '2025-08-02 09:00:00');
