-- Role grants that make the local stack usable, kept separate on purpose.
--
-- 33_internal.sql is a faithful copy of the H2 test fixture, and that fixture is deliberately
-- minimal: it grants four mappings chosen to cover every branch of role resolution (a normal
-- grant, a role this release no longer defines, and a deactivated mapping). Adding rows to it
-- would weaken the tests that count those mappings.
--
-- But the same four mappings leave the developer identity asserted by
-- DevWebSealRequestHeaderAuthenticationFilter - groups AMS_INTERNAL_OPERATIONS and
-- AMS_INTERNAL_ADMIN - holding only INT_SEARCH_ASSETS, INT_VIEW_ASSET and INT_ADMIN_UTILITIES.
-- Every other screen answers "Not permitted", including the dashboard the welcome page redirects
-- to, so the application looks broken on first use when it is behaving exactly as configured.
--
-- These rows give those two groups a realistic operator and administrator role set. They exist
-- only in Oracle; the H2 fixture is untouched.

-- Operations: everything a service desk agent does day to day.
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_DASHBOARD', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_ATTENTION_QUEUE', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_CLEAR_ATTENTION_FLAG', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_ASSET_HISTORY', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_ASSET_CONFIG_HISTORY', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_COMPARE_CONFIG', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_SEARCH_CUSTOMERS', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_CUSTOMER', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_CONTACTS', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_SERVICES', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_ORDER', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_CREATE_ORDER', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_SELECT_ASSET', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_SUBMIT_ORDER', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_SAVE_ORDER_FOR_LATER', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_CANCEL_ORDER', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_CALENDAR', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_SCHEDULE_TECHLINE', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_SCHEDULE_INSTALLATION', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_RESCHEDULE_INSTALLATION', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_NCR', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_NCR_HISTORY', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_CREATE_NCR', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_RMA', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_VIEW_TERMS', 'Y');

-- Administration: the state-changing and configuration screens, kept off the operations group so
-- the split between the two is visible in the running application rather than only in the code.
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_VIEW_DASHBOARD', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_CUSTOMER_ADMIN', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_ENABLE_ORDERING', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_EDIT_CONTACTS', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_VIEW_QUEUES', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_REQUEUE_FAILED_WORK', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_EDIT_PROPERTIES', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_MODIFY_CONFIG', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_RESOLVE_CONFIG_MISMATCH', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_DECOMMISSION_ASSET', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_SCHEDULE_DECOMMISSION', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_CANCEL_DECOMMISSION', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_UPDATE_INSTALL_ADDRESS', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_MOVE_ASSET', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_SUBMIT_NCR', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_CANCEL_NCR', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_RESCHEDULE_NCR', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_CREATE_RMA', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_UPDATE_RMA', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_EMERGENCY_REPLACEMENT', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_ENABLE_EMERGENCY_REPLACEMENT', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_ADMIN', 'INT_OVERRIDE_DUE_DILIGENCE', 'Y');

-- Deliberately NOT granted to anyone: INT_CHANGE_USER and INT_OVERRIDE_CURRENT_TIME. Those gate
-- the non-production impersonation screen, which can rebuild the caller's own authentication.
-- Leaving them ungranted keeps that screen unreachable even in the local stack; grant them by hand
-- if you need to exercise it.

-- Provisioning: despatch the order, then record the visit as done.
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_DESPATCH_ORDER', 'Y');
INSERT INTO AMS_LDAP_GROUP_ROLES (LDAP_GROUP_NAME, ROLE_CD, ACTIVE_FL) VALUES ('AMS_INTERNAL_OPERATIONS', 'INT_COMPLETE_INSTALLATION', 'Y');
