-- Flag columns are Y/N only. Declared as constraints rather than trusted from the code,
-- because ConversionUtils.getBoolean treats anything that is not 'Y' as false - so a bad
-- value would read as a silent 'no' rather than an error.

ALTER TABLE AMS_ADDRESSES ADD CONSTRAINT IF NOT EXISTS ADDRESSES_VALIDATED_CK CHECK (VALIDATED_FL IN ('Y','N'));
ALTER TABLE AMS_ASSETS ADD CONSTRAINT IF NOT EXISTS ASSETS_MIGRATABLE_CK CHECK (MIGRATABLE_FL IN ('Y','N'));
ALTER TABLE AMS_ASSETS ADD CONSTRAINT IF NOT EXISTS ASSETS_EMERGENCY_REPL_CK CHECK (EMERGENCY_REPL_FL IN ('Y','N'));
ALTER TABLE AMS_ASSETS ADD CONSTRAINT IF NOT EXISTS ASSETS_NEEDS_ATTENTION_CK CHECK (NEEDS_ATTENTION_FL IN ('Y','N'));
ALTER TABLE AMS_CONTACTS ADD CONSTRAINT IF NOT EXISTS CONTACTS_ACTIVE_CK CHECK (ACTIVE_FL IN ('Y','N'));
ALTER TABLE AMS_CUSTOMERS ADD CONSTRAINT IF NOT EXISTS CUSTOMERS_CAN_SUBMIT_ORDERS_CK CHECK (CAN_SUBMIT_ORDERS_FL IN ('Y','N'));
ALTER TABLE AMS_CUSTOMERS ADD CONSTRAINT IF NOT EXISTS CUSTOMERS_ACTIVE_CK CHECK (ACTIVE_FL IN ('Y','N'));
ALTER TABLE AMS_CUSTOMER_EARLY_ADOPTERS ADD CONSTRAINT IF NOT EXISTS CUSTOMER_EARLY_ADOPTERS_EARLY_ CHECK (EARLY_ADOPTER_FL IN ('Y','N'));
ALTER TABLE AMS_DECOMMISSIONS ADD CONSTRAINT IF NOT EXISTS DECOMMISSIONS_HARDWARE_RETURN_ CHECK (HARDWARE_RETURN_FL IN ('Y','N'));
ALTER TABLE AMS_LDAP_GROUP_ROLES ADD CONSTRAINT IF NOT EXISTS LDAP_GROUP_ROLES_ACTIVE_CK CHECK (ACTIVE_FL IN ('Y','N'));
ALTER TABLE AMS_MAINTENANCE_WINDOWS ADD CONSTRAINT IF NOT EXISTS MAINTENANCE_WINDOWS_ENABLED_CK CHECK (ENABLED_FL IN ('Y','N'));
ALTER TABLE AMS_ORDERS ADD CONSTRAINT IF NOT EXISTS ORDERS_CANCEL_PENALTY_CK CHECK (CANCEL_PENALTY_FL IN ('Y','N'));
ALTER TABLE AMS_PORT_CONFIGS ADD CONSTRAINT IF NOT EXISTS PORT_CONFIGS_ACTIVE_CK CHECK (ACTIVE_FL IN ('Y','N'));
ALTER TABLE AMS_TIMESLOTS ADD CONSTRAINT IF NOT EXISTS TIMESLOTS_AVAILABLE_CK CHECK (AVAILABLE_FL IN ('Y','N'));

-- A holiday is a day, not an instant: CalendarDAOImpl compares it with TRUNC.
ALTER TABLE AMS_HOLIDAYS ADD CONSTRAINT IF NOT EXISTS HOLIDAYS_DT_CK CHECK (HOLIDAY_DT = TRUNC(HOLIDAY_DT));

-- Turns any future counter bug into an immediate ORA-02290 instead of a double-booked engineer.
ALTER TABLE AMS_TIMESLOTS ADD CONSTRAINT IF NOT EXISTS TIMESLOTS_RESERVED_CK
  CHECK (RESERVED_COUNT >= 0 AND RESERVED_COUNT <= CAPACITY);

-- The two ledger tables the procedures own.
ALTER TABLE AMS_TIMESLOT_RESERVATIONS ADD CONSTRAINT IF NOT EXISTS TSRES_STATUS_CK
  CHECK (RESERVATION_STATUS_CD IN ('HELD','RELEASED'));
ALTER TABLE AMS_CIRCUIT_WINDOWS ADD CONSTRAINT IF NOT EXISTS CIRCWIN_STATUS_CK
  CHECK (WINDOW_STATUS_CD IN ('RESERVED','RELEASED','COMPLETED'));

-- Subscriber PCs captured with the order.
ALTER TABLE AMS_SUBSCRIBER_PCS ADD CONSTRAINT IF NOT EXISTS SUBPC_STATIC_CK CHECK (STATIC_FL IN ('Y','N'));
-- A seat count of zero would make the LAN sizing on the order meaningless; the form defaults to 1.
ALTER TABLE AMS_SUBSCRIBER_PCS ADD CONSTRAINT IF NOT EXISTS SUBPC_USER_COUNT_CK
  CHECK (USER_COUNT IS NULL OR USER_COUNT > 0);

-- A maintenance window belongs to an asset or to an order, never to both and never to neither.
-- Enforced here because the two paths write it from different screens and nothing else would
-- notice an orphan.
-- Written out longhand rather than as (ASSET_ID IS NULL) <> (ORDER_ID IS NULL): comparing two
-- boolean expressions is legal in PL/SQL but not in SQL, and would fail to compile here.
ALTER TABLE AMS_MAINTENANCE_WINDOWS ADD CONSTRAINT IF NOT EXISTS MAINTWIN_OWNER_CK
  CHECK ((ASSET_ID IS NOT NULL AND ORDER_ID IS NULL)
      OR (ASSET_ID IS NULL AND ORDER_ID IS NOT NULL));
