-- Foreign keys, selectively.
--
-- Added only where the parent is unambiguous. Deliberately NOT added to AMS_EVENTS.ENTITY_ID or
-- AMS_EMAIL_QUEUE.ENTITY_ID: those columns are polymorphic across five entity types (order, asset,
-- NCR, RMA, decommission), so there is no single table to point at and no constraint that could
-- express it. The check constraints in 10_check_constraints.sql carry the rest of the integrity.
--
-- Every one of these is nullable on the child side, which matters: a new-install order has no
-- asset yet, and OrderDAOImpl.insertOrder binds NULL for ASSET_ID in that case.

ALTER TABLE AMS_ASSETS ADD CONSTRAINT IF NOT EXISTS ASSETS_CUSTOMER_FK
  FOREIGN KEY (CUSTOMER_ID) REFERENCES AMS_CUSTOMERS (CUSTOMER_ID);

ALTER TABLE AMS_CONTACTS ADD CONSTRAINT IF NOT EXISTS CONTACTS_CUSTOMER_FK
  FOREIGN KEY (CUSTOMER_ID) REFERENCES AMS_CUSTOMERS (CUSTOMER_ID);

ALTER TABLE AMS_SERVICES ADD CONSTRAINT IF NOT EXISTS SERVICES_CUSTOMER_FK
  FOREIGN KEY (CUSTOMER_ID) REFERENCES AMS_CUSTOMERS (CUSTOMER_ID);

ALTER TABLE AMS_CUSTOMER_EARLY_ADOPTERS ADD CONSTRAINT IF NOT EXISTS CUSTEA_CUSTOMER_FK
  FOREIGN KEY (CUSTOMER_ID) REFERENCES AMS_CUSTOMERS (CUSTOMER_ID);

ALTER TABLE AMS_ORDERS ADD CONSTRAINT IF NOT EXISTS ORDERS_CUSTOMER_FK
  FOREIGN KEY (CUSTOMER_ID) REFERENCES AMS_CUSTOMERS (CUSTOMER_ID);
ALTER TABLE AMS_ORDERS ADD CONSTRAINT IF NOT EXISTS ORDERS_ASSET_FK
  FOREIGN KEY (ASSET_ID) REFERENCES AMS_ASSETS (ASSET_ID);

ALTER TABLE AMS_ASSET_CONFIGS ADD CONSTRAINT IF NOT EXISTS ASSETCFG_ASSET_FK
  FOREIGN KEY (ASSET_ID) REFERENCES AMS_ASSETS (ASSET_ID);

ALTER TABLE AMS_PORT_CONFIGS ADD CONSTRAINT IF NOT EXISTS PORTCFG_CONFIG_FK
  FOREIGN KEY (CONFIG_ID) REFERENCES AMS_ASSET_CONFIGS (CONFIG_ID);

ALTER TABLE AMS_DECOMMISSIONS ADD CONSTRAINT IF NOT EXISTS DECOM_ASSET_FK
  FOREIGN KEY (ASSET_ID) REFERENCES AMS_ASSETS (ASSET_ID);

ALTER TABLE AMS_ASSET_RETURNS ADD CONSTRAINT IF NOT EXISTS ASSETRET_ASSET_FK
  FOREIGN KEY (ASSET_ID) REFERENCES AMS_ASSETS (ASSET_ID);

ALTER TABLE AMS_RMAS ADD CONSTRAINT IF NOT EXISTS RMAS_ASSET_FK
  FOREIGN KEY (ASSET_ID) REFERENCES AMS_ASSETS (ASSET_ID);

ALTER TABLE AMS_MAINTENANCE_WINDOWS ADD CONSTRAINT IF NOT EXISTS MAINTWIN_ASSET_FK
  FOREIGN KEY (ASSET_ID) REFERENCES AMS_ASSETS (ASSET_ID);

ALTER TABLE AMS_NETWORK_CHANGE_REQUESTS ADD CONSTRAINT IF NOT EXISTS NCR_CUSTOMER_FK
  FOREIGN KEY (CUSTOMER_ID) REFERENCES AMS_CUSTOMERS (CUSTOMER_ID);
ALTER TABLE AMS_NETWORK_CHANGE_REQUESTS ADD CONSTRAINT IF NOT EXISTS NCR_ASSET_FK
  FOREIGN KEY (ASSET_ID) REFERENCES AMS_ASSETS (ASSET_ID);

-- A child table proper: an NCR type row is meaningless without its request.
ALTER TABLE AMS_NCR_TYPES ADD CONSTRAINT IF NOT EXISTS NCRTYPES_NCR_FK
  FOREIGN KEY (NCR_ID) REFERENCES AMS_NETWORK_CHANGE_REQUESTS (NCR_ID) ON DELETE CASCADE;

ALTER TABLE AMS_CUSTOMER_SCHEDULES ADD CONSTRAINT IF NOT EXISTS CUSTSCHED_CUSTOMER_FK
  FOREIGN KEY (CUSTOMER_ID) REFERENCES AMS_CUSTOMERS (CUSTOMER_ID);

ALTER TABLE AMS_INSTALLATIONS ADD CONSTRAINT IF NOT EXISTS INSTALL_ORDER_FK
  FOREIGN KEY (ORDER_ID) REFERENCES AMS_ORDERS (ORDER_ID);
ALTER TABLE AMS_INSTALLATIONS ADD CONSTRAINT IF NOT EXISTS INSTALL_ASSET_FK
  FOREIGN KEY (ASSET_ID) REFERENCES AMS_ASSETS (ASSET_ID);

ALTER TABLE AMS_TERMS_ACCEPTANCES ADD CONSTRAINT IF NOT EXISTS TERMSACC_VERSION_FK
  FOREIGN KEY (VERSION) REFERENCES AMS_TERMS_AND_CONDITIONS (VERSION);

ALTER TABLE AMS_CUSTOMER_VISITS ADD CONSTRAINT IF NOT EXISTS CUSTVISIT_CUSTOMER_FK
  FOREIGN KEY (CUSTOMER_ID) REFERENCES AMS_CUSTOMERS (CUSTOMER_ID);

-- The two ledger tables.
ALTER TABLE AMS_TIMESLOT_RESERVATIONS ADD CONSTRAINT IF NOT EXISTS TSRES_TIMESLOT_FK
  FOREIGN KEY (TIMESLOT_ID) REFERENCES AMS_TIMESLOTS (TIMESLOT_ID);
ALTER TABLE AMS_CIRCUIT_WINDOWS ADD CONSTRAINT IF NOT EXISTS CIRCWIN_NCR_FK
  FOREIGN KEY (NCR_ID) REFERENCES AMS_NETWORK_CHANGE_REQUESTS (NCR_ID);
ALTER TABLE AMS_CIRCUIT_WINDOWS ADD CONSTRAINT IF NOT EXISTS CIRCWIN_TIMESLOT_FK
  FOREIGN KEY (TIMESLOT_ID) REFERENCES AMS_TIMESLOTS (TIMESLOT_ID);

-- Nullable and set after the fact by UpdateInstallAddressAction, so this cannot constrain the
-- insert order of AMS_ASSETS at runtime - only the seed has to respect it.
ALTER TABLE AMS_ASSETS ADD CONSTRAINT IF NOT EXISTS ASSETS_INSTALL_ADDR_FK
  FOREIGN KEY (INSTALL_ADDRESS_ID) REFERENCES AMS_ADDRESSES (ADDRESS_ID);

-- The ordering flow's captured data.
--
-- All nullable on the child side: the steps are completed one screen at a time and a
-- saved-for-later order is a partly populated one, so an order row legitimately exists with any
-- subset of these still unset.
ALTER TABLE AMS_SUBSCRIBER_PCS ADD CONSTRAINT IF NOT EXISTS SUBPC_ORDER_FK
  FOREIGN KEY (ORDER_ID) REFERENCES AMS_ORDERS (ORDER_ID);

ALTER TABLE AMS_ORDERS ADD CONSTRAINT IF NOT EXISTS ORDERS_SHIP_ADDR_FK
  FOREIGN KEY (SHIP_ADDRESS_ID) REFERENCES AMS_ADDRESSES (ADDRESS_ID);
ALTER TABLE AMS_ORDERS ADD CONSTRAINT IF NOT EXISTS ORDERS_ORDER_CONTACT_FK
  FOREIGN KEY (ORDER_CONTACT_ID) REFERENCES AMS_CONTACTS (CONTACT_ID);
ALTER TABLE AMS_ORDERS ADD CONSTRAINT IF NOT EXISTS ORDERS_SHIP_CONTACT_FK
  FOREIGN KEY (SHIP_CONTACT_ID) REFERENCES AMS_CONTACTS (CONTACT_ID);
ALTER TABLE AMS_ORDERS ADD CONSTRAINT IF NOT EXISTS ORDERS_INSTALL_CONTACT_FK
  FOREIGN KEY (INSTALL_CONTACT_ID) REFERENCES AMS_CONTACTS (CONTACT_ID);
ALTER TABLE AMS_ORDERS ADD CONSTRAINT IF NOT EXISTS ORDERS_SHIP_WINDOW_FK
  FOREIGN KEY (SHIP_WINDOW_ID) REFERENCES AMS_TIMESLOTS (TIMESLOT_ID);

-- MAINT_WINDOW_ID and CONFIG_ID are deliberately left unconstrained in the other direction:
-- AMS_MAINTENANCE_WINDOWS.ORDER_ID and AMS_ASSET_CONFIGS.ORDER_ID already point back here, and
-- adding the reverse key as well would make the pair mutually dependent and unsavable in one pass.
ALTER TABLE AMS_MAINTENANCE_WINDOWS ADD CONSTRAINT IF NOT EXISTS MAINTWIN_ORDER_FK
  FOREIGN KEY (ORDER_ID) REFERENCES AMS_ORDERS (ORDER_ID);
ALTER TABLE AMS_ASSET_CONFIGS ADD CONSTRAINT IF NOT EXISTS ASSETCFG_ORDER_FK
  FOREIGN KEY (ORDER_ID) REFERENCES AMS_ORDERS (ORDER_ID);
