-- Indexes.
--
-- Two groups. First, every foreign key column: Oracle takes a share lock on the whole child table
-- when a parent row is updated or deleted through an unindexed FK, which under concurrency shows
-- up as unrelated sessions blocking each other. Second, the columns the DAOs and the scheduling
-- procedures actually filter on, taken from their SQL rather than guessed.

-- ---------- foreign key columns ----------
CREATE INDEX IF NOT EXISTS ASSETS_CUSTOMER_IX        ON AMS_ASSETS (CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS CONTACTS_CUSTOMER_IX      ON AMS_CONTACTS (CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS SERVICES_CUSTOMER_IX      ON AMS_SERVICES (CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS ORDERS_CUSTOMER_IX        ON AMS_ORDERS (CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS ORDERS_ASSET_IX           ON AMS_ORDERS (ASSET_ID);
CREATE INDEX IF NOT EXISTS ASSETCFG_ASSET_IX         ON AMS_ASSET_CONFIGS (ASSET_ID);
CREATE INDEX IF NOT EXISTS PORTCFG_CONFIG_IX         ON AMS_PORT_CONFIGS (CONFIG_ID);
CREATE INDEX IF NOT EXISTS DECOM_ASSET_IX            ON AMS_DECOMMISSIONS (ASSET_ID);
CREATE INDEX IF NOT EXISTS ASSETRET_ASSET_IX         ON AMS_ASSET_RETURNS (ASSET_ID);
CREATE INDEX IF NOT EXISTS RMAS_ASSET_IX             ON AMS_RMAS (ASSET_ID);
CREATE INDEX IF NOT EXISTS MAINTWIN_ASSET_IX         ON AMS_MAINTENANCE_WINDOWS (ASSET_ID);
CREATE INDEX IF NOT EXISTS NCR_CUSTOMER_IX           ON AMS_NETWORK_CHANGE_REQUESTS (CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS NCR_ASSET_IX              ON AMS_NETWORK_CHANGE_REQUESTS (ASSET_ID);
CREATE INDEX IF NOT EXISTS CUSTSCHED_CUSTOMER_IX     ON AMS_CUSTOMER_SCHEDULES (CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS INSTALL_ORDER_IX          ON AMS_INSTALLATIONS (ORDER_ID);
CREATE INDEX IF NOT EXISTS INSTALL_ASSET_IX          ON AMS_INSTALLATIONS (ASSET_ID);
CREATE INDEX IF NOT EXISTS TERMSACC_VERSION_IX       ON AMS_TERMS_ACCEPTANCES (VERSION);
CREATE INDEX IF NOT EXISTS CUSTVISIT_CUSTOMER_IX     ON AMS_CUSTOMER_VISITS (CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS TSRES_TIMESLOT_IX         ON AMS_TIMESLOT_RESERVATIONS (TIMESLOT_ID);
CREATE INDEX IF NOT EXISTS CIRCWIN_NCR_IX            ON AMS_CIRCUIT_WINDOWS (NCR_ID);
CREATE INDEX IF NOT EXISTS CIRCWIN_TIMESLOT_IX       ON AMS_CIRCUIT_WINDOWS (TIMESLOT_ID);

-- ---------- query predicates ----------

-- CalendarDAOImpl / CalendarServiceDAOImpl slot lookups, and the CIRCUIT calendar the
-- site-type NCR procedure reads by region and day.
CREATE INDEX IF NOT EXISTS TIMESLOTS_TYPE_START_IX   ON AMS_TIMESLOTS (CALL_TYPE_CD, START_TM);
CREATE INDEX IF NOT EXISTS TIMESLOTS_TYPE_REGION_IX  ON AMS_TIMESLOTS (CALL_TYPE_CD, REGION_CD, START_TM);

-- AssetDAOImpl.getMigratableAssetsForCustomer tests "no open order for this asset".
CREATE INDEX IF NOT EXISTS ORDERS_ASSET_STATUS_IX    ON AMS_ORDERS (ASSET_ID, ORDER_STATUS_CD);
CREATE INDEX IF NOT EXISTS NCR_ASSET_STATUS_IX       ON AMS_NETWORK_CHANGE_REQUESTS (ASSET_ID, NCR_STATUS_CD);
CREATE INDEX IF NOT EXISTS DECOM_ASSET_STATUS_IX     ON AMS_DECOMMISSIONS (ASSET_ID, DECOM_STATUS_CD);
CREATE INDEX IF NOT EXISTS ASSETCFG_ASSET_STATUS_IX  ON AMS_ASSET_CONFIGS (ASSET_ID, CONFIG_STATUS_CD);

-- Search and lookup paths.
CREATE INDEX IF NOT EXISTS ASSETS_SERIAL_IX          ON AMS_ASSETS (UPPER(SERIAL_NUMBER));
CREATE INDEX IF NOT EXISTS ASSETS_TAG_IX             ON AMS_ASSETS (UPPER(ASSET_TAG));
CREATE INDEX IF NOT EXISTS ASSETS_ATTENTION_IX       ON AMS_ASSETS (NEEDS_ATTENTION_FL, MODIFIED_DT);
CREATE INDEX IF NOT EXISTS ORDERS_NUMBER_IX          ON AMS_ORDERS (UPPER(ORDER_NUMBER));
CREATE INDEX IF NOT EXISTS CUSTOMERS_ACCOUNT_IX      ON AMS_CUSTOMERS (ACCOUNT_NUMBER);
CREATE INDEX IF NOT EXISTS CUSTOMERS_NAME_IX         ON AMS_CUSTOMERS (UPPER(CUSTOMER_NAME));

-- AmsUserDetailsDAOImpl resolves roles on every single request, so this one is on the hot path.
CREATE INDEX IF NOT EXISTS LDAPROLES_GROUP_IX        ON AMS_LDAP_GROUP_ROLES (UPPER(LDAP_GROUP_NAME), ACTIVE_FL);

-- AMS_EMAIL_PG resolves recipients here; the poller and the dedup check use the queue indexes.
CREATE INDEX IF NOT EXISTS CONTACTS_CUST_TYPE_IX     ON AMS_CONTACTS (CUSTOMER_ID, CONTACT_TYPE_CD, ACTIVE_FL);
CREATE INDEX IF NOT EXISTS EMAILQ_STATUS_IX          ON AMS_EMAIL_QUEUE (EMAIL_STATUS_CD, CREATED_DT);
CREATE INDEX IF NOT EXISTS EMAILQ_DEDUP_IX           ON AMS_EMAIL_QUEUE (ENTITY_TYPE_CD, ENTITY_ID, TEMPLATE_CD, CREATED_DT);

-- History tabs and the work queues.
CREATE INDEX IF NOT EXISTS EVENTS_ENTITY_IX          ON AMS_EVENTS (ENTITY_TYPE_CD, ENTITY_ID, EVENT_DT);
CREATE INDEX IF NOT EXISTS MODQUEUE_NAME_STATUS_IX   ON AMS_MODIFY_QUEUE (QUEUE_NAME, QUEUE_STATUS_CD, CREATED_DT);
CREATE INDEX IF NOT EXISTS SAVEFORLATER_USER_IX      ON AMS_SAVE_FOR_LATER (USER_ID, SAVE_TYPE_CD);
CREATE INDEX IF NOT EXISTS ETLRUNS_JOB_IX            ON AMS_ETL_RUNS (JOB_NAME, RUN_DT);

-- CalendarDAOImpl.isHoliday wraps the column in TRUNC, which makes a plain index unusable.
CREATE INDEX IF NOT EXISTS HOLIDAYS_TRUNC_IX         ON AMS_HOLIDAYS (TRUNC(HOLIDAY_DT));

-- Lets reserve_timeslot find an existing HELD reservation without scanning the ledger.
CREATE INDEX IF NOT EXISTS TSRES_LOOKUP_IX           ON AMS_TIMESLOT_RESERVATIONS (TIMESLOT_ID, ENTITY_TYPE_CD, ENTITY_ID, RESERVATION_STATUS_CD);
CREATE INDEX IF NOT EXISTS CIRCWIN_NCR_STATUS_IX     ON AMS_CIRCUIT_WINDOWS (NCR_ID, WINDOW_STATUS_CD);

-- The ordering flow reads every one of these back by its owning order.
CREATE INDEX IF NOT EXISTS AMS_SUBSCRIBER_PCS_ORDER_IX ON AMS_SUBSCRIBER_PCS (ORDER_ID);
CREATE INDEX IF NOT EXISTS AMS_MAINT_WINDOWS_ORDER_IX ON AMS_MAINTENANCE_WINDOWS (ORDER_ID);
CREATE INDEX IF NOT EXISTS AMS_ASSET_CONFIGS_ORDER_IX ON AMS_ASSET_CONFIGS (ORDER_ID);
