-- Sequences.
--
-- START WITH 100000, not the 1000 the H2 fixtures use. Seeded ids run 1001-9901, so a
-- sequence starting at 1000 would hand out an id that already exists the first time it is
-- called - and the failure would be a constraint violation on an unrelated insert.

CREATE SEQUENCE IF NOT EXISTS AMS_ADDRESSES_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_ASSETS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_ASSET_CONFIGS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_ASSET_RETURNS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_CONTACTS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_DECOMMISSIONS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_EMAIL_QUEUE_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_EVENTS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_MODIFY_QUEUE_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_NCR_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_ORDERS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_RMAS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_SAVE_FOR_LATER_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_TIMESLOTS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;

-- The two ledger tables added for the scheduling procedures.
CREATE SEQUENCE IF NOT EXISTS AMS_TIMESLOT_RESERVATIONS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE IF NOT EXISTS AMS_CIRCUIT_WINDOWS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;

-- Subscriber PCs captured with an order.
CREATE SEQUENCE IF NOT EXISTS AMS_SUBSCRIBER_PCS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;
-- The maintenance window chosen while ordering is inserted, not updated: until this flow existed
-- the only writer was an UPDATE against an existing asset row, so the table never needed one.
CREATE SEQUENCE IF NOT EXISTS AMS_MAINT_WINDOWS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE;

-- Installations were previously only ever seeded, so nothing needed to generate an id for one.
-- Provisioning creates one per despatched order, so it does.
CREATE SEQUENCE AMS_INSTALLATIONS_SQ START WITH 100000 INCREMENT BY 1 NOCACHE NOCYCLE;
