-- AMS_TIMESLOTS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_TIMESLOTS (
  TIMESLOT_ID     NUMBER(19) NOT NULL,
  CALL_TYPE_CD    VARCHAR2(20 CHAR),
  REGION_CD       VARCHAR2(20 CHAR),
  START_TM        TIMESTAMP,
  END_TM          TIMESTAMP,
  CAPACITY        NUMBER(10),
  RESERVED_COUNT  NUMBER(10) DEFAULT 0,
  AVAILABLE_FL    VARCHAR2(1 CHAR) DEFAULT 'Y',
  DISPLAY_LABEL   VARCHAR2(80 CHAR),
  TIME_ZONE       VARCHAR2(40 CHAR),
  CONSTRAINT AMS_TIMESLOTS_PK PRIMARY KEY (TIMESLOT_ID)
);
