-- AMS_NETWORK_CHANGE_REQUESTS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_NETWORK_CHANGE_REQUESTS (
  NCR_ID               NUMBER(19) NOT NULL,
  REQUEST_NUMBER       VARCHAR2(40 CHAR),
  ASSET_ID             NUMBER(19),
  CUSTOMER_ID          NUMBER(19),
  NCR_STATUS_CD        VARCHAR2(20 CHAR),
  REQUESTED_DT         TIMESTAMP,
  SUBMITTED_DT         TIMESTAMP,
  SCHEDULED_DT         TIMESTAMP,
  COMPLETED_DT         TIMESTAMP,
  CANCELLED_DT         TIMESTAMP,
  CANCELLATION_REASON  VARCHAR2(400 CHAR),
  COMMENTS             VARCHAR2(2000),
  CREATED_DT           TIMESTAMP,
  CREATED_BY           VARCHAR2(64 CHAR),
  MODIFIED_DT          TIMESTAMP,
  MODIFIED_BY          VARCHAR2(64 CHAR),
  CONSTRAINT AMS_NETWORK_CHANGE_REQUESTS_PK PRIMARY KEY (NCR_ID)
);
