-- AMS_CONTACTS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_CONTACTS (
  CONTACT_ID       NUMBER(19) NOT NULL,
  CUSTOMER_ID      NUMBER(19),
  FIRST_NAME       VARCHAR2(60 CHAR),
  LAST_NAME        VARCHAR2(60 CHAR),
  EMAIL_ADDRESS    VARCHAR2(120 CHAR),
  PHONE_NUMBER     VARCHAR2(30 CHAR),
  PHONE_EXTENSION  VARCHAR2(10 CHAR),
  MOBILE_NUMBER    VARCHAR2(30 CHAR),
  CONTACT_TYPE_CD  VARCHAR2(20 CHAR),
  ACTIVE_FL        VARCHAR2(1 CHAR) DEFAULT 'Y',
  CREATED_DT       TIMESTAMP,
  CREATED_BY       VARCHAR2(64 CHAR),
  MODIFIED_DT      TIMESTAMP,
  MODIFIED_BY      VARCHAR2(64 CHAR),
  CONSTRAINT AMS_CONTACTS_PK PRIMARY KEY (CONTACT_ID)
);
