-- AMS_TERMS_ACCEPTANCES
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_TERMS_ACCEPTANCES (
  USER_ID      VARCHAR2(64 CHAR) NOT NULL,
  VERSION      VARCHAR2(20 CHAR) NOT NULL,
  ACCEPTED_DT  TIMESTAMP,
  CONSTRAINT AMS_TERMS_ACCEPTANCES_PK PRIMARY KEY (USER_ID, VERSION)
);
