-- AMS_PORT_CONFIGS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_PORT_CONFIGS (
  PORT_ID         NUMBER(19) NOT NULL,
  CONFIG_ID       NUMBER(19),
  PORT_NAME       VARCHAR2(30 CHAR),
  PORT_CONFIG_CD  VARCHAR2(20 CHAR),
  MAC_ADDRESS     VARCHAR2(20 CHAR),
  ACTIVE_FL       VARCHAR2(1 CHAR) DEFAULT 'Y',
  VLAN_ID         NUMBER(10),
  IP_ADDRESS      VARCHAR2(15 CHAR),
  SUBNET_MASK     VARCHAR2(15 CHAR),
  CONSTRAINT AMS_PORT_CONFIGS_PK PRIMARY KEY (PORT_ID)
);
