-- AMS_ADDRESSES
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_ADDRESSES (
  ADDRESS_ID       NUMBER(19) NOT NULL,
  ADDRESS_TYPE_CD  VARCHAR2(20 CHAR),
  ADDRESS_LINE_1   VARCHAR2(80 CHAR),
  ADDRESS_LINE_2   VARCHAR2(80 CHAR),
  CITY             VARCHAR2(60 CHAR),
  ZIP_CODE         VARCHAR2(15 CHAR),
  COUNTY           VARCHAR2(60 CHAR),
  STATE_CD         VARCHAR2(4 CHAR),
  COUNTRY_CD       VARCHAR2(4 CHAR),
  ATTENTION_TO     VARCHAR2(80 CHAR),
  VALIDATED_FL     VARCHAR2(1 CHAR) DEFAULT 'N',
  CREATED_DT       TIMESTAMP,
  CREATED_BY       VARCHAR2(64 CHAR),
  MODIFIED_DT      TIMESTAMP,
  MODIFIED_BY      VARCHAR2(64 CHAR),
  CONSTRAINT AMS_ADDRESSES_PK PRIMARY KEY (ADDRESS_ID)
);
