-- AMS_HOLIDAYS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_HOLIDAYS (
  HOLIDAY_DT    TIMESTAMP NOT NULL,
  HOLIDAY_NAME  VARCHAR2(80 CHAR),
  CONSTRAINT AMS_HOLIDAYS_PK PRIMARY KEY (HOLIDAY_DT)
);
