-- AMS_CUSTOMER_SCHEDULES
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_CUSTOMER_SCHEDULES (
  CUSTOMER_SCHEDULE_ID  NUMBER(19) NOT NULL,
  CUSTOMER_ID           NUMBER(19),
  BLACKOUT_DT           TIMESTAMP,
  REASON                VARCHAR2(200 CHAR),
  CONSTRAINT AMS_CUSTOMER_SCHEDULES_PK PRIMARY KEY (CUSTOMER_SCHEDULE_ID)
);
