-- AMS_CUSTOMER_VISITS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_CUSTOMER_VISITS (
  USER_ID      VARCHAR2(64 CHAR) NOT NULL,
  CUSTOMER_ID  NUMBER(19) NOT NULL,
  VISITED_DT   TIMESTAMP,
  CONSTRAINT AMS_CUSTOMER_VISITS_PK PRIMARY KEY (USER_ID, CUSTOMER_ID)
);
