-- AMS_TERMS_AND_CONDITIONS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_TERMS_AND_CONDITIONS (
  VERSION       VARCHAR2(20 CHAR) NOT NULL,
  EFFECTIVE_DT  TIMESTAMP,
  DOCUMENT_URL  VARCHAR2(400 CHAR),
  CONSTRAINT AMS_TERMS_AND_CONDITIONS_PK PRIMARY KEY (VERSION)
);
