-- AMS_INSTALLATIONS
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_INSTALLATIONS (
  INSTALLATION_ID     NUMBER(19) NOT NULL,
  ASSET_ID            NUMBER(19),
  ORDER_ID            NUMBER(19),
  INSTALL_STATUS_CD   VARCHAR2(20 CHAR),
  SCHEDULED_DT        TIMESTAMP,
  TIMESLOT_ID         NUMBER(19),
  INSTALL_ADDRESS_ID  NUMBER(19),
  INSTALL_CONTACT_ID  NUMBER(19),
  TECHNICIAN_NAME     VARCHAR2(120 CHAR),
  NOTES               VARCHAR2(2000),
  COMPLETED_DT        TIMESTAMP,
  CREATED_DT          TIMESTAMP,
  CREATED_BY          VARCHAR2(64 CHAR),
  MODIFIED_DT         TIMESTAMP,
  MODIFIED_BY         VARCHAR2(64 CHAR),
  CONSTRAINT AMS_INSTALLATIONS_PK PRIMARY KEY (INSTALLATION_ID)
);
