-- AMS_SAVE_FOR_LATER
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_SAVE_FOR_LATER (
  SAVE_FOR_LATER_ID  NUMBER(19) NOT NULL,
  USER_ID            VARCHAR2(64 CHAR),
  CUSTOMER_ID        NUMBER(19),
  SAVE_TYPE_CD       VARCHAR2(20 CHAR),
  PAYLOAD            VARCHAR2(4000),
  CREATED_DT         TIMESTAMP,
  MODIFIED_DT        TIMESTAMP,
  CONSTRAINT AMS_SAVE_FOR_LATER_PK PRIMARY KEY (SAVE_FOR_LATER_ID)
);
