-- AMS_LDAP_GROUP_ROLES
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_LDAP_GROUP_ROLES (
  LDAP_GROUP_NAME  VARCHAR2(120 CHAR) NOT NULL,
  ROLE_CD          VARCHAR2(80 CHAR) NOT NULL,
  ACTIVE_FL        VARCHAR2(1 CHAR) DEFAULT 'Y',
  CONSTRAINT AMS_LDAP_GROUP_ROLES_PK PRIMARY KEY (LDAP_GROUP_NAME, ROLE_CD)
);
