-- AMS_LOADABLE_TYPES
-- Generated from the H2 test fixture; edit that and re-run the translator.
CREATE TABLE IF NOT EXISTS AMS_LOADABLE_TYPES (
  TYPE_ID      NUMBER(19) NOT NULL,
  TYPE_NAME    VARCHAR2(60 CHAR),
  TYPE_CD      VARCHAR2(60 CHAR),
  DESCRIPTION  VARCHAR2(200 CHAR),
  SORT_ORDER   NUMBER(10),
  CONSTRAINT AMS_LOADABLE_TYPES_PK PRIMARY KEY (TYPE_ID)
);
