CREATE TABLE AMS_CUSTOMER_VISITS (
  USER_ID               VARCHAR(64) NOT NULL,
  CUSTOMER_ID           NUMBER(19) NOT NULL,
  VISITED_DT            TIMESTAMP,
  PRIMARY KEY (USER_ID, CUSTOMER_ID)
);
