-- AMS_DECOMMISSIONS
CREATE TABLE AMS_DECOMMISSIONS (
  DECOMMISSION_ID       NUMBER(19) NOT NULL PRIMARY KEY,
  ASSET_ID              NUMBER(19),
  DECOM_STATUS_CD       VARCHAR(20),
  REQUESTED_DT          TIMESTAMP,
  SCHEDULED_DT          TIMESTAMP,
  COMPLETED_DT          TIMESTAMP,
  REASON                VARCHAR(400),
  HARDWARE_RETURN_FL    CHAR(1) DEFAULT 'N',
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
