-- AMS_INSTALLATIONS
CREATE TABLE AMS_INSTALLATIONS (
  INSTALLATION_ID       NUMBER(19) NOT NULL PRIMARY KEY,
  ASSET_ID              NUMBER(19),
  ORDER_ID              NUMBER(19),
  INSTALL_STATUS_CD     VARCHAR(20),
  SCHEDULED_DT          TIMESTAMP,
  TIMESLOT_ID           NUMBER(19),
  INSTALL_ADDRESS_ID    NUMBER(19),
  INSTALL_CONTACT_ID    NUMBER(19),
  TECHNICIAN_NAME       VARCHAR(120),
  NOTES                 VARCHAR(2000),
  COMPLETED_DT          TIMESTAMP,
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
