-- AMS_ADDRESSES
CREATE TABLE AMS_ADDRESSES (
  ADDRESS_ID            NUMBER(19) NOT NULL PRIMARY KEY,
  ADDRESS_TYPE_CD       VARCHAR(20),
  ADDRESS_LINE_1        VARCHAR(80),
  ADDRESS_LINE_2        VARCHAR(80),
  CITY                  VARCHAR(60),
  ZIP_CODE              VARCHAR(15),
  COUNTY                VARCHAR(60),
  STATE_CD              VARCHAR(4),
  COUNTRY_CD            VARCHAR(4),
  ATTENTION_TO          VARCHAR(80),
  VALIDATED_FL          CHAR(1) DEFAULT 'N',
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
