-- AMS_SAVE_FOR_LATER
CREATE TABLE AMS_SAVE_FOR_LATER (
  SAVE_FOR_LATER_ID     NUMBER(19) NOT NULL PRIMARY KEY,
  USER_ID               VARCHAR(64),
  CUSTOMER_ID           NUMBER(19),
  SAVE_TYPE_CD          VARCHAR(20),
  PAYLOAD               VARCHAR(4000),
  CREATED_DT            TIMESTAMP,
  MODIFIED_DT           TIMESTAMP
);
