-- AMS_MODIFY_QUEUE
CREATE TABLE AMS_MODIFY_QUEUE (
  QUEUE_ID              NUMBER(19) NOT NULL PRIMARY KEY,
  QUEUE_NAME            VARCHAR(40),
  ENTITY_REFERENCE      VARCHAR(80),
  PAYLOAD               VARCHAR(4000),
  QUEUE_STATUS_CD       VARCHAR(20),
  ATTEMPT_COUNT         NUMBER(10) DEFAULT 0,
  FAILURE_REASON        VARCHAR(1000),
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
