-- AMS_MAINTENANCE_WINDOWS
CREATE TABLE AMS_MAINTENANCE_WINDOWS (
  MAINT_WINDOW_ID       NUMBER(19) NOT NULL PRIMARY KEY,
  ASSET_ID              NUMBER(19),
  ORDER_ID              NUMBER(19),
  DAY_CD                VARCHAR(10),
  START_HOUR_CD         VARCHAR(10),
  END_HOUR_CD           VARCHAR(10),
  TIME_ZONE             VARCHAR(40),
  ENABLED_FL            CHAR(1) DEFAULT 'Y',
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
