-- AMS_NETWORK_CHANGE_REQUESTS
CREATE TABLE AMS_NETWORK_CHANGE_REQUESTS (
  NCR_ID                NUMBER(19) NOT NULL PRIMARY KEY,
  REQUEST_NUMBER        VARCHAR(40),
  ASSET_ID              NUMBER(19),
  CUSTOMER_ID           NUMBER(19),
  NCR_STATUS_CD         VARCHAR(20),
  REQUESTED_DT          TIMESTAMP,
  SUBMITTED_DT          TIMESTAMP,
  SCHEDULED_DT          TIMESTAMP,
  COMPLETED_DT          TIMESTAMP,
  CANCELLED_DT          TIMESTAMP,
  CANCELLATION_REASON   VARCHAR(400),
  COMMENTS              VARCHAR(2000),
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
