-- AMS_EVENTS
CREATE TABLE AMS_EVENTS (
  EVENT_ID              NUMBER(19) NOT NULL PRIMARY KEY,
  EVENT_TYPE_CD         VARCHAR(20),
  ENTITY_TYPE_CD        VARCHAR(20),
  ENTITY_ID             NUMBER(19),
  DESCRIPTION           VARCHAR(1000),
  USER_ID               VARCHAR(64),
  USER_DISPLAY_NAME     VARCHAR(120),
  DATA_SOURCE_CD        VARCHAR(20),
  EVENT_DT              TIMESTAMP
);
