-- AMS_SUBSCRIBER_PCS
CREATE TABLE AMS_SUBSCRIBER_PCS (
  SUBSCRIBER_PC_ID      NUMBER(19) NOT NULL PRIMARY KEY,
  ORDER_ID              NUMBER(19),
  HOST_NAME             VARCHAR(60),
  PC_TYPE_CD            VARCHAR(20),
  OPERATING_SYSTEM      VARCHAR(60),
  MAC_ADDRESS           VARCHAR(20),
  IP_ADDRESS            VARCHAR(15),
  STATIC_FL             CHAR(1) DEFAULT 'N',
  USER_COUNT            NUMBER(10),
  NOTES                 VARCHAR(400),
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
