-- AMS_ASSETS
CREATE TABLE AMS_ASSETS (
  ASSET_ID              NUMBER(19) NOT NULL PRIMARY KEY,
  CUSTOMER_ID           NUMBER(19),
  ASSET_TAG             VARCHAR(40),
  LEGACY_ASSET_TAG      VARCHAR(40),
  SERIAL_NUMBER         VARCHAR(60),
  ASSET_TYPE_CD         VARCHAR(20),
  ASSET_STATUS_CD       VARCHAR(20),
  DATA_SOURCE_CD        VARCHAR(20),
  INSTALL_ADDRESS_ID    NUMBER(19),
  MIGRATABLE_FL         CHAR(1) DEFAULT 'N',
  EMERGENCY_REPL_FL     CHAR(1) DEFAULT 'N',
  NEEDS_ATTENTION_FL    CHAR(1) DEFAULT 'N',
  ATTENTION_REASON      VARCHAR(200),
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
