-- AMS_CUSTOMER_EARLY_ADOPTERS
CREATE TABLE AMS_CUSTOMER_EARLY_ADOPTERS (
  CUSTOMER_ID           NUMBER(19) NOT NULL PRIMARY KEY,
  EARLY_ADOPTER_FL      CHAR(1) DEFAULT 'N',
  ENROLLED_DT           TIMESTAMP,
  PROGRAM_NAME          VARCHAR(80)
);
