-- AMS_CUSTOMERS
CREATE TABLE AMS_CUSTOMERS (
  CUSTOMER_ID           NUMBER(19) NOT NULL PRIMARY KEY,
  CUSTOMER_NAME         VARCHAR(120),
  CUSTOMER_SHORT_NAME   VARCHAR(40),
  ACCOUNT_NUMBER        VARCHAR(20),
  CAN_SUBMIT_ORDERS_FL  CHAR(1) DEFAULT 'N',
  ACTIVE_FL             CHAR(1) DEFAULT 'Y',
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
