-- AMS_TIMESLOTS
CREATE TABLE AMS_TIMESLOTS (
  TIMESLOT_ID           NUMBER(19) NOT NULL PRIMARY KEY,
  CALL_TYPE_CD          VARCHAR(20),
  REGION_CD             VARCHAR(20),
  START_TM              TIMESTAMP,
  END_TM                TIMESTAMP,
  CAPACITY              NUMBER(10),
  RESERVED_COUNT        NUMBER(10) DEFAULT 0,
  AVAILABLE_FL          CHAR(1) DEFAULT 'Y',
  DISPLAY_LABEL         VARCHAR(80),
  TIME_ZONE             VARCHAR(40)
);
