-- AMS_PROPERTIES
CREATE TABLE AMS_PROPERTIES (
  PROPERTY_KEY          VARCHAR(60) NOT NULL PRIMARY KEY,
  PROPERTY_VALUE        VARCHAR(400),
  DESCRIPTION           VARCHAR(400),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
