-- AMS_RMAS
CREATE TABLE AMS_RMAS (
  RMA_ID                NUMBER(19) NOT NULL PRIMARY KEY,
  RMA_NUMBER            VARCHAR(40),
  ASSET_ID              NUMBER(19),
  ASSET_TAG             VARCHAR(40),
  TRACKING_NUMBER       VARCHAR(60),
  SHIPPING_CARRIER_CD   VARCHAR(20),
  RMA_STATUS_CD         VARCHAR(20),
  ISSUED_DT             TIMESTAMP,
  DUE_DT                TIMESTAMP,
  RECEIVED_DT           TIMESTAMP,
  REASON                VARCHAR(400),
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
