-- AMS_EMAIL_QUEUE
CREATE TABLE AMS_EMAIL_QUEUE (
  EMAIL_ID              NUMBER(19) NOT NULL PRIMARY KEY,
  TEMPLATE_CD           VARCHAR(20),
  ENTITY_TYPE_CD        VARCHAR(20),
  ENTITY_ID             NUMBER(19),
  TO_ADDRESS            VARCHAR(200),
  EMAIL_STATUS_CD       VARCHAR(20),
  FAILURE_REASON        VARCHAR(1000),
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
