-- AMS_CONTACTS
CREATE TABLE AMS_CONTACTS (
  CONTACT_ID            NUMBER(19) NOT NULL PRIMARY KEY,
  CUSTOMER_ID           NUMBER(19),
  FIRST_NAME            VARCHAR(60),
  LAST_NAME             VARCHAR(60),
  EMAIL_ADDRESS         VARCHAR(120),
  PHONE_NUMBER          VARCHAR(30),
  PHONE_EXTENSION       VARCHAR(10),
  MOBILE_NUMBER         VARCHAR(30),
  CONTACT_TYPE_CD       VARCHAR(20),
  ACTIVE_FL             CHAR(1) DEFAULT 'Y',
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
