-- AMS_ETL_RUNS
CREATE TABLE AMS_ETL_RUNS (
  ETL_RUN_ID            NUMBER(19) NOT NULL PRIMARY KEY,
  JOB_NAME              VARCHAR(60),
  ETL_STATUS_CD         VARCHAR(20),
  RUN_DT                TIMESTAMP,
  ROWS_PROCESSED        NUMBER(19)
);
