-- AMS_TERMS_AND_CONDITIONS
CREATE TABLE AMS_TERMS_AND_CONDITIONS (
  VERSION               VARCHAR(20) NOT NULL PRIMARY KEY,
  EFFECTIVE_DT          TIMESTAMP,
  DOCUMENT_URL          VARCHAR(400)
);
