-- AMS_SERVICES
CREATE TABLE AMS_SERVICES (
  SERVICE_ID            NUMBER(19) NOT NULL PRIMARY KEY,
  CUSTOMER_ID           NUMBER(19),
  SERVICE_TYPE_CD       VARCHAR(20),
  SERVICE_STATUS_CD     VARCHAR(20),
  START_DT              TIMESTAMP,
  END_DT                TIMESTAMP,
  DESCRIPTION           VARCHAR(200),
  EXTERNAL_SERVICE_REF  VARCHAR(60),
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
