-- AMS_TERMS_ACCEPTANCES
CREATE TABLE AMS_TERMS_ACCEPTANCES (
  USER_ID               VARCHAR(64) NOT NULL,
  VERSION               VARCHAR(20) NOT NULL,
  ACCEPTED_DT           TIMESTAMP,
  PRIMARY KEY (USER_ID, VERSION)
);
