-- AMS_ASSET_RETURNS
CREATE TABLE AMS_ASSET_RETURNS (
  ASSET_RETURN_ID       NUMBER(19) NOT NULL PRIMARY KEY,
  ASSET_ID              NUMBER(19),
  SERIAL_NUMBER         VARCHAR(60),
  RETURN_STATUS_CD      VARCHAR(20),
  CREATED_DT            TIMESTAMP,
  CREATED_BY            VARCHAR(64),
  MODIFIED_DT           TIMESTAMP,
  MODIFIED_BY           VARCHAR(64)
);
