-- AMS_LOADABLE_TYPES
CREATE TABLE AMS_LOADABLE_TYPES (
  TYPE_ID               NUMBER(19) NOT NULL PRIMARY KEY,
  TYPE_NAME             VARCHAR(60),
  TYPE_CD               VARCHAR(60),
  DESCRIPTION           VARCHAR(200),
  SORT_ORDER            NUMBER(10)
);
