-- AMS_CUSTOMER_SCHEDULES
CREATE TABLE AMS_CUSTOMER_SCHEDULES (
  CUSTOMER_SCHEDULE_ID  NUMBER(19) NOT NULL PRIMARY KEY,
  CUSTOMER_ID           NUMBER(19),
  BLACKOUT_DT           TIMESTAMP,
  REASON                VARCHAR(200)
);
