-- AMS_PORT_CONFIGS
CREATE TABLE AMS_PORT_CONFIGS (
  PORT_ID               NUMBER(19) NOT NULL PRIMARY KEY,
  CONFIG_ID             NUMBER(19),
  PORT_NAME             VARCHAR(30),
  PORT_CONFIG_CD        VARCHAR(20),
  MAC_ADDRESS           VARCHAR(20),
  ACTIVE_FL             CHAR(1) DEFAULT 'Y',
  VLAN_ID               NUMBER(10),
  IP_ADDRESS            VARCHAR(15),
  SUBNET_MASK           VARCHAR(15)
);
